<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GenTRAC.DataBridge.Standard\GenTRAC.DataBridge.Standard.csproj" />
    <ProjectReference Include="..\IES.DataBridge.Standard\IES.DataBridge.Standard.csproj" />
    <ProjectReference Include="..\IES.Standard\IES.Standard.csproj" />
  </ItemGroup>

</Project>
