<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Configurations>Debug;Release;ReleaseTFSCore</Configurations>
	<SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="logs\log-*.csv" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="parameters.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="parameters.xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IES.ActionLogic.Core\IES.ActionLogic.Core.csproj" />
    <ProjectReference Include="..\IES.Common.Core\IES.Common.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="logs\" />
  </ItemGroup>

</Project>
