//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BurdenPoolLU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BurdenPoolLU()
        {
            this.ProPricerBurdenRateMaps = new HashSet<ProPricerBurdenRateMap>();
            this.RateCodes = new HashSet<RateCode>();
            this.RateCodes1 = new HashSet<RateCode>();
        }
    
        public int ID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string BurdenPool { get; set; }
        public string Description { get; set; }
        public bool IsGaT2ApplicableForMissionSolutions { get; set; }
        public int RevisionID { get; set; }
        public bool IsCommercial { get; set; }
        public bool ExcludeFCCOM { get; set; }
        public bool IncludeGaT2InBurdAndCommBurdTables { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProPricerBurdenRateMap> ProPricerBurdenRateMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateCode> RateCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateCode> RateCodes1 { get; set; }
        public virtual Revision Revision { get; set; }
    }
}
