//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CobraFiscalYearLU
    {
        public int ID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Year { get; set; }
        public System.DateTime FiscalYearStartDate { get; set; }
    }
}
