//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAttachment
    {
        public int FileAttachmentId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public Nullable<int> SectionId { get; set; }
        public int RevisionId { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
