//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProPricerBurdenRateMap
    {
        public int ID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int BurdenPoolID { get; set; }
        public int BurdenElementID { get; set; }
        public int RateCodeID { get; set; }
    
        public virtual BurdenElementLU BurdenElementLU { get; set; }
        public virtual BurdenPoolLU BurdenPoolLU { get; set; }
        public virtual RateCode RateCode { get; set; }
    }
}
