//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProPricerRateCodeXref
    {
        public int ID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int RateCodeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> RateCodeExtensionID { get; set; }
        public Nullable<int> ResourceClassID { get; set; }
    
        public virtual RateCode RateCode { get; set; }
        public virtual RateCodeExtensionLU RateCodeExtensionLU { get; set; }
        public virtual ResourceClassLU ResourceClassLU { get; set; }
    }
}
