//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RateCode()
        {
            this.ProPricerBurdenRateMaps = new HashSet<ProPricerBurdenRateMap>();
            this.ProPricerRateCodeXrefs = new HashSet<ProPricerRateCodeXref>();
            this.RateCodeYears = new HashSet<RateCodeYear>();
            this.RDSBRateCodeXrefs = new HashSet<RDSBRateCodeXref>();
        }
    
        public int ID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int RevisionID { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string RateCode1 { get; set; }
        public Nullable<int> ResourceTypeID { get; set; }
        public Nullable<int> GovernmentBurdenPoolID { get; set; }
        public Nullable<int> CommercialBurdenPoolID { get; set; }
        public Nullable<int> RateTypeID { get; set; }
        public string CobraRateSet { get; set; }
        public Nullable<int> CobraCode1ID { get; set; }
    
        public virtual BurdenPoolLU CommercialBurdenPoolLU { get; set; }
        public virtual BurdenPoolLU GovernmentBurdenPoolLU { get; set; }
        public virtual CategoryLU CategoryLU { get; set; }
        public virtual CobraCode1LU CobraCode1LU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProPricerBurdenRateMap> ProPricerBurdenRateMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProPricerRateCodeXref> ProPricerRateCodeXrefs { get; set; }
        public virtual RateCode RateCode11 { get; set; }
        public virtual RateCode RateCode2 { get; set; }
        public virtual RateTypeLU RateTypeLU { get; set; }
        public virtual ResourceTypeLU ResourceTypeLU { get; set; }
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateCodeYear> RateCodeYears { get; set; }
        public virtual Revision Revision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDSBRateCodeXref> RDSBRateCodeXrefs { get; set; }
    }
}
