//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDSBDocumentInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RDSBDocumentInformation()
        {
            this.RDSBRateCodeXrefs = new HashSet<RDSBRateCodeXref>();
            this.RDSBSectionXrefs = new HashSet<RDSBSectionXref>();
        }
    
        public int ID { get; set; }
        public int PTMProposalID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdateDT { get; set; }
        public int RDMRevisionID { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndYear { get; set; }
        public string ParentSection { get; set; }
    
        public virtual Revision Revision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDSBRateCodeXref> RDSBRateCodeXrefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDSBSectionXref> RDSBSectionXrefs { get; set; }
    }
}
