//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDSBSectionXref
    {
        public int ID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int SectionID { get; set; }
        public int RDSBDocumentInformationID { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual RDSBDocumentInformation RDSBDocumentInformation { get; set; }
    }
}
