//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Revision()
        {
            this.BurdenPoolLUs = new HashSet<BurdenPoolLU>();
            this.RateCodes = new HashSet<RateCode>();
            this.Sections = new HashSet<Section>();
            this.RDSBDocumentInformations = new HashSet<RDSBDocumentInformation>();
        }
    
        public int ID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Revision1 { get; set; }
        public string History { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public string PublishedBy { get; set; }
        public int StartYear { get; set; }
        public int EndYear { get; set; }
        public string ReleaseNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BurdenPoolLU> BurdenPoolLUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateCode> RateCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDSBDocumentInformation> RDSBDocumentInformations { get; set; }
    }
}
