//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.RateCodes = new HashSet<RateCode>();
            this.Section1 = new HashSet<Section>();
            this.FileAttachments = new HashSet<FileAttachment>();
            this.RDSBSectionXrefs = new HashSet<RDSBSectionXref>();
        }
    
        public int ID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int RevisionID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int DisplayOrder { get; set; }
        public string Title { get; set; }
        public string TextContent { get; set; }
        public int SectionContentTypeID { get; set; }
        public bool IsInternalSection { get; set; }
        public bool DisplayRateCode { get; set; }
        public int RevisionUniqueSectionId { get; set; }
        public bool IsRdsbRequired { get; set; }
        public bool SectionContainsCasbDisclosure { get; set; }
		public bool IsDisclosureStatementAdequate { get; set; }
        public bool SectionContainsNonCompliance { get; set; }
		public bool NonComplianceNotification { get; set; }
        public string Office { get; set; }
        public string Agency { get; set; }
        public string LMBA { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string CityST { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Other { get; set; }
        public Nullable<bool> IncludeInCoversheet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateCode> RateCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Section1 { get; set; }
        public virtual Section Section2 { get; set; }
        public virtual SectionContentTypeLU SectionContentTypeLU { get; set; }
        public virtual Revision Revision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileAttachment> FileAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDSBSectionXref> RDSBSectionXrefs { get; set; }
    }
}
