<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Configurations>Debug;Release;ReleaseTFSCore</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GenBOE.DataBridge.Core\GenBOE.DataBridge.Core.csproj" />
    <ProjectReference Include="..\GenTRAC.DataBridge.Core\GenTRAC.DataBridge.Core.csproj" />
    <ProjectReference Include="..\IES.Common.Core\IES.Common.Core.csproj" />
    <ProjectReference Include="..\IES.DataBridge.Core\IES.DataBridge.Core.csproj" />
  </ItemGroup>

</Project>
