// -----------------------------------------------------------------------
// <copyright company="Lockheed Martin Corporation">
//     Copyright (c) 2011 - 2020 Lockheed Martin Corporation
// </copyright>
// <autogenerated />
// -----------------------------------------------------------------------

namespace GenTRAC.Tests.DAL.Common
{
    using System;
    using System.Collections.Generic;
    using GenTRAC.DataBridge.Common.Security;
    using GenTRAC.DataBridge.DTO;
    using IES.Common;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Moq;

    /// <summary>
    /// Test Security Access
    /// </summary>
    [TestClass]
    public class SecurityAccessTest
    {
        /// <summary>
        /// Proposal Loader
        /// </summary>
        private Mock<IProposalLoader> proposalLoader = null;

        /// <summary>
        /// Initialize
        /// </summary>
        [TestInitialize]
        public void Initialize()
        {
            proposalLoader = new Mock<IProposalLoader>();
        }

        /// <summary>
        /// Run a test case based on the parameters passed in
        /// </summary>
        /// <param name="inAuthorizedRoles">The authorized roles to test the users permissions for</param>
        /// <param name="inRequestedPages">The requested pages to test the permissions</param>
        /// <param name="inProposalId">The ID of the Proposal</param>
        /// <param name="inExpectedAuthorization">The expected authorization based on the parameters</param>
        private void TestExecution(PtmRole[] inAuthorizedRoles,
            PtmSecurityPage[] inRequestedPages,
            int? inProposalId,
            SecurityAuthorization inExpectedAuthorization,
            bool proposalIdMismatch = false)
        {
            // test for selected pages
            foreach (PtmSecurityPage page in inRequestedPages)
            {
                SecurityPermissionsRequested requestedPermissions = null;
                SecurityAccess sut = this.TestSetup(page, // securitypage
                    inProposalId, // requested Proposal ID
                    inAuthorizedRoles, // authorized roles
                    (inProposalId.HasValue && proposalIdMismatch) ? inProposalId.Value + 1 : inProposalId , // authorized Proposal ID
                    out requestedPermissions); // permissions object itself

                PtmRole highestRole;
                SecurityAuthorization authorization = sut.IsAuthorized(requestedPermissions, out highestRole);

                Assert.AreEqual(inExpectedAuthorization, authorization);
            }
        }

        /// <summary>
        /// Setup the permissions requested object for test usage
        /// </summary>
        /// <param name="inPageRequested">page enum being requested</param>
        /// <param name="inRequestedProposalID">proposal id being requested</param>
        /// <param name="inAuthorizedRoles">authorized roles to return to caller from security call</param>
        /// <param name="inAuthorizedProposalID">authorized capture to return to caller from security call</param>
        /// <param name="outRequestedPermissions">the requested permission object to be passed to "IsAuthorized"</param>
        /// <returns>A configured Security Access object</returns>
        private SecurityAccess TestSetup(PtmSecurityPage inPageRequested,
            int? inRequestedProposalId,
            PtmRole[] inAuthorizedRoles,
            int? inAuthorizedProposalId,
            out SecurityPermissionsRequested outRequestedPermissions)
        {
            #region secpermissionsrequested setup
            // build a request object
            SecurityPermissionsRequested requestedPermission = new SecurityPermissionsRequested();
            requestedPermission.PageToCheck = inPageRequested;
            requestedPermission.ProposalId = inRequestedProposalId;
            #endregion secpermissionsrequested setup

            // assign the request object to the out parm so the caller now has it
            outRequestedPermissions = requestedPermission;

            #region secpermissionsrequested setup
            // build the response we will use in the mock object for what the user is actually authorized for
            List<SecurityPermissionsResponse> authorizedPermissions = new List<SecurityPermissionsResponse>();

            foreach (PtmRole role in inAuthorizedRoles)
            {
                SecurityPermissionsResponse authorizedPermission = new SecurityPermissionsResponse(role, inAuthorizedProposalId);
                authorizedPermissions.Add(authorizedPermission);
            }
            #endregion secpermissionsrequested setup

            #region secmapper setup
            // mock the securitymapper to return the authorized permissions collection we setup
            var securityMapper = new Mock<ISecurityMapper>();
            securityMapper.Setup(x => x.GetRolesForLoggedInUser()).
                Returns(authorizedPermissions);
            #endregion secmapper setup

            SecurityAccess sut = new SecurityAccess(securityMapper.Object, this.proposalLoader.Object);

            return sut;
        }

        /// <summary>
        /// Is Authorized test
        /// </summary>
        [TestMethod]
        public void IsAuthorizedTest()
        {
            // HOME PAGE
            // not set - CRUD
            this.TestExecution(new PtmRole[] { PtmRole.NotSet }, new PtmSecurityPage[] { PtmSecurityPage.Home }, null, SecurityAuthorization.CreateReadUpdateDelete);

            // admin - none
            this.TestExecution(new PtmRole[] { PtmRole.Admin }, new PtmSecurityPage[] { PtmSecurityPage.Home }, null, SecurityAuthorization.None);

            // ADMIN PAGE
            // admin - CRUD
            this.TestExecution(new PtmRole[] { PtmRole.Admin }, new PtmSecurityPage[] { PtmSecurityPage.Admin }, null, SecurityAuthorization.CreateReadUpdateDelete);

            // pricer - no permissions
            this.TestExecution(new PtmRole[] { PtmRole.Pricer }, new PtmSecurityPage[] { PtmSecurityPage.Admin }, null, SecurityAuthorization.None);

            // REPORTS PAGE
            // admin - read
            this.TestExecution(new PtmRole[] { PtmRole.Admin }, new PtmSecurityPage[] { PtmSecurityPage.Reports }, null, SecurityAuthorization.Read);

            // pricer - no permissions
            this.TestExecution(new PtmRole[] { PtmRole.Pricer }, new PtmSecurityPage[] { PtmSecurityPage.Reports }, null, SecurityAuthorization.None);

            // PROPOSAL PAGE
            // pricer with no proposal - no permissions
            this.TestExecution(new PtmRole[] { PtmRole.Pricer }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, null, SecurityAuthorization.None);
            this.TestExecution(new PtmRole[] { PtmRole.PeerReviewer }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, null, SecurityAuthorization.None);
            this.TestExecution(new PtmRole[] { PtmRole.PricingVerification }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, null, SecurityAuthorization.None);
            this.TestExecution(new PtmRole[] { PtmRole.CoverSheetApprover }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, null, SecurityAuthorization.None);
            this.TestExecution(new PtmRole[] { PtmRole.LOBEstLead }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, null, SecurityAuthorization.None);
            

            // setup proposal
            int proposalId = 15;
            ProposalDto proposal = new ProposalDto()
            {
                Id = proposalId,
                ProposalStatus = ProposalStatus.InProgress
            };
            this.proposalLoader.Setup(x => x.GetById(proposalId)).Returns(proposal);
            this.proposalLoader.Setup(x => x.GetProposalStatus(proposalId)).Returns(ProposalStatus.InProgress);

            // pricer with proposal Id mismatch - no permissions
            this.TestExecution(new PtmRole[] { PtmRole.Pricer }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.None, true);

            // pricer with proposal - read update
            this.TestExecution(new PtmRole[] { PtmRole.Pricer }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.CreateReadUpdateDelete);
            this.TestExecution(new PtmRole[] { PtmRole.CoverSheetApprover }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.Read);
            this.TestExecution(new PtmRole[] { PtmRole.PricingVerification }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.Read);
            this.TestExecution(new PtmRole[] { PtmRole.LOBEstLead }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.Read);
            this.TestExecution(new PtmRole[] { PtmRole.PeerReviewer }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.Read);

            proposal.IsForecastProposal = true;
            this.TestExecution(new PtmRole[] { PtmRole.LOBEstLead }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.CreateReadUpdateDelete);
            proposal.IsForecastProposal = false;

            // capture manager with proposal - read
            this.TestExecution(new PtmRole[] { PtmRole.CaptureManager }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.Read);

            // admin with proposal - CRUD
            this.TestExecution(new PtmRole[] { PtmRole.Admin }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.CreateReadUpdateDelete);

            // Proposal Setup admin -read update
            this.TestExecution(new PtmRole[] { PtmRole.ProposalSetupAdmin }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.ReadUpdate);

            proposal.ProposalStatus = ProposalStatus.Deleted;
            this.proposalLoader.Setup(x => x.GetProposalStatus(proposalId)).Returns(ProposalStatus.Deleted);

            // admin with deleted proposal - CRUD
            this.TestExecution(new PtmRole[] { PtmRole.Admin }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.CreateReadUpdateDelete);

            // pricer with deleted proposal - no permissions
            this.TestExecution(new PtmRole[] { PtmRole.Pricer }, new PtmSecurityPage[] { PtmSecurityPage.Proposal }, proposalId, SecurityAuthorization.None);

            proposal.ProposalStatus = ProposalStatus.InProgress;
            this.proposalLoader.Setup(x => x.GetProposalStatus(proposalId)).Returns(ProposalStatus.InProgress);

            // CHECKLIST PAGE (proposal required)
            // pricer - CRUD
            this.TestExecution(new PtmRole[] { PtmRole.Pricer }, new PtmSecurityPage[] { PtmSecurityPage.Checklist }, proposalId, SecurityAuthorization.CreateReadUpdateDelete);

            // capture manager - read
            this.TestExecution(new PtmRole[] { PtmRole.CaptureManager }, new PtmSecurityPage[] { PtmSecurityPage.Checklist }, proposalId, SecurityAuthorization.Read);

            // My Approvals tab
            // Does not need tested since Home page is CreateUpdate for everyone

            // APPROVALS TAB on Proposal page (proposal required)
            this.TestExecution(new PtmRole[] { PtmRole.Pricer }, new PtmSecurityPage[] { PtmSecurityPage.Approvals }, proposalId, SecurityAuthorization.ReadUpdate);
            this.TestExecution(new PtmRole[] { PtmRole.CoverSheetApprover }, new PtmSecurityPage[] { PtmSecurityPage.Approvals }, proposalId, SecurityAuthorization.ReadUpdate);
            this.TestExecution(new PtmRole[] { PtmRole.PricingVerification }, new PtmSecurityPage[] { PtmSecurityPage.Approvals }, proposalId, SecurityAuthorization.ReadUpdate);
            this.TestExecution(new PtmRole[] { PtmRole.LOBEstLead }, new PtmSecurityPage[] { PtmSecurityPage.Approvals }, proposalId, SecurityAuthorization.ReadUpdate);
            this.TestExecution(new PtmRole[] { PtmRole.PeerReviewer }, new PtmSecurityPage[] { PtmSecurityPage.Approvals }, proposalId, SecurityAuthorization.ReadUpdate);
            this.TestExecution(new PtmRole[] { PtmRole.Admin }, new PtmSecurityPage[] { PtmSecurityPage.Approvals }, proposalId, SecurityAuthorization.Read);
        }

        /// <summary>
        /// Current User Has Role test
        /// </summary>
        [TestMethod]
        public void CurrentUserHasRoleTest()
        {
            SecurityPermissionsRequested permission = null;
            int proposalId = 15;
            SecurityAccess sut = this.TestSetup(PtmSecurityPage.Proposal, null, new PtmRole[] { PtmRole.Pricer, PtmRole.Admin }, null, out permission);
            Assert.IsFalse(sut.CurrentUserHasRole(PtmRole.Pricer, proposalId));
            Assert.IsTrue(sut.CurrentUserHasRole(PtmRole.Admin, null));

            sut = this.TestSetup(PtmSecurityPage.Proposal, proposalId, new PtmRole[] { PtmRole.Pricer, PtmRole.Admin }, proposalId, out permission);
            Assert.IsTrue(sut.CurrentUserHasRole(PtmRole.Pricer, proposalId));
            Assert.IsTrue(sut.CurrentUserHasRole(PtmRole.Admin, null));
        }

        /// <summary>
        /// Exception test
        /// </summary>
        [TestMethod]
        [ExpectedException(typeof(ArgumentException), "The proposal ID is required for security checks and was not supplied for page type Checklist")]
        public void IsAuthorized_RequiredProposalIdExceptionTest()
        {
            // CHECKLIST PAGE
            // no proposal - exception
            PtmRole[] roles = new PtmRole[] { PtmRole.Pricer };
            this.TestExecution(roles, new PtmSecurityPage[] { PtmSecurityPage.Checklist }, null, SecurityAuthorization.None);
        }
    }
}
