<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IES.Core\IES.Core.csproj" />
    <ProjectReference Include="..\IES.Models.Standard\IES.Models.Standard.csproj" />
  </ItemGroup>

</Project>
