<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="IdentitySwappingScript.js" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="IdentitySwappingScript.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.DirectoryServices" Version="8.0.0" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Identity Swapping Instructions.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
