//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenBOE.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BOEImporterTest {
            get {
                object obj = ResourceManager.GetObject("BOEImporterTest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportCost {
            get {
                object obj = ResourceManager.GetObject("LaborImportCost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportCostDecimalPrecision {
            get {
                object obj = ResourceManager.GetObject("LaborImportCostDecimalPrecision", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportCostEmptyCost {
            get {
                object obj = ResourceManager.GetObject("LaborImportCostEmptyCost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportCostInvalidTotal {
            get {
                object obj = ResourceManager.GetObject("LaborImportCostInvalidTotal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportCostMissingCost {
            get {
                object obj = ResourceManager.GetObject("LaborImportCostMissingCost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportCostSpreadDecimalPrecision {
            get {
                object obj = ResourceManager.GetObject("LaborImportCostSpreadDecimalPrecision", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportCostSpreadRangeInvalid {
            get {
                object obj = ResourceManager.GetObject("LaborImportCostSpreadRangeInvalid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportCostSpreadTooLarge {
            get {
                object obj = ResourceManager.GetObject("LaborImportCostSpreadTooLarge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportCostTooLarge {
            get {
                object obj = ResourceManager.GetObject("LaborImportCostTooLarge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportEPs {
            get {
                object obj = ResourceManager.GetObject("LaborImportEPs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImporterBadFormat {
            get {
                object obj = ResourceManager.GetObject("LaborImporterBadFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImporterNotExcel {
            get {
                object obj = ResourceManager.GetObject("LaborImporterNotExcel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHours {
            get {
                object obj = ResourceManager.GetObject("LaborImportHours", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursChangeCurve {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursChangeCurve", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursChangeCurveAndRateType {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursChangeCurveAndRateType", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursCustomFields {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursCustomFields", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursCustomFieldsMulti {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursCustomFieldsMulti", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursCustomFieldsNoChange {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursCustomFieldsNoChange", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursCustomFieldsNoSelection {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursCustomFieldsNoSelection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursInvalidDates {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursInvalidDates", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursInvalidEnd {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursInvalidEnd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursInvalidPerfOrg {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursInvalidPerfOrg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursInvalidResource {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursInvalidResource", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursInvalidStart {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursInvalidStart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursInvalidTotal {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursInvalidTotal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursPercentage {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursPercentage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportHoursSpreadInvalidDecimal {
            get {
                object obj = ResourceManager.GetObject("LaborImportHoursSpreadInvalidDecimal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportInvalidResourceId {
            get {
                object obj = ResourceManager.GetObject("LaborImportInvalidResourceId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportInvalidSpreadData {
            get {
                object obj = ResourceManager.GetObject("LaborImportInvalidSpreadData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportMissingEndDate {
            get {
                object obj = ResourceManager.GetObject("LaborImportMissingEndDate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportMissingPerfOrg {
            get {
                object obj = ResourceManager.GetObject("LaborImportMissingPerfOrg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportMissingResource {
            get {
                object obj = ResourceManager.GetObject("LaborImportMissingResource", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportMissingSpreadCurve {
            get {
                object obj = ResourceManager.GetObject("LaborImportMissingSpreadCurve", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportMissingStartDate {
            get {
                object obj = ResourceManager.GetObject("LaborImportMissingStartDate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportMultiClin {
            get {
                object obj = ResourceManager.GetObject("LaborImportMultiClin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] laborimportmulticustomfields {
            get {
                object obj = ResourceManager.GetObject("laborimportmulticustomfields", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportMultiNull {
            get {
                object obj = ResourceManager.GetObject("LaborImportMultiNull", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportMultiWBS {
            get {
                object obj = ResourceManager.GetObject("LaborImportMultiWBS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportNoRows {
            get {
                object obj = ResourceManager.GetObject("LaborImportNoRows", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportSpreadDataDecimalsTooLong {
            get {
                object obj = ResourceManager.GetObject("LaborImportSpreadDataDecimalsTooLong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportSpreadDataExtraMonth {
            get {
                object obj = ResourceManager.GetObject("LaborImportSpreadDataExtraMonth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportSpreadDataInvalidStartMonth {
            get {
                object obj = ResourceManager.GetObject("LaborImportSpreadDataInvalidStartMonth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportSpreadDataInvalidStartMonth0 {
            get {
                object obj = ResourceManager.GetObject("LaborImportSpreadDataInvalidStartMonth0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportSpreadDataLargerSum {
            get {
                object obj = ResourceManager.GetObject("LaborImportSpreadDataLargerSum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportSpreadDataMissingMonth {
            get {
                object obj = ResourceManager.GetObject("LaborImportSpreadDataMissingMonth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportSpreadDataMissingValue {
            get {
                object obj = ResourceManager.GetObject("LaborImportSpreadDataMissingValue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportSpreadDataTooLong {
            get {
                object obj = ResourceManager.GetObject("LaborImportSpreadDataTooLong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborImportSpreadDataValidStartMonth {
            get {
                object obj = ResourceManager.GetObject("LaborImportSpreadDataValidStartMonth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LaborTypesAndSpread {
            get {
                object obj = ResourceManager.GetObject("LaborTypesAndSpread", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MOQTableRMS {
            get {
                object obj = ResourceManager.GetObject("MOQTableRMS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MOQTableRMSInvalid {
            get {
                object obj = ResourceManager.GetObject("MOQTableRMSInvalid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MoqTableRmsValid {
            get {
                object obj = ResourceManager.GetObject("MoqTableRmsValid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MOQTableSSC {
            get {
                object obj = ResourceManager.GetObject("MOQTableSSC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MOQTableSSCInvalid {
            get {
                object obj = ResourceManager.GetObject("MOQTableSSCInvalid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MoqTableSscValid {
            get {
                object obj = ResourceManager.GetObject("MoqTableSscValid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectMap {
            get {
                object obj = ResourceManager.GetObject("ProjectMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WbsBoeReport {
            get {
                object obj = ResourceManager.GetObject("WbsBoeReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Workoffline {
            get {
                object obj = ResourceManager.GetObject("Workoffline", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
