<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
    <PackageReference Include="Moq" Version="4.18.4" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProPricerWebApi\ProPricerWebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <Reference Include="DevExpress.Data.v22.2">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\DevExpress.Data.v22.2.dll</HintPath>
	  </Reference>
	  <Reference Include="DevExpress.Drawing.v22.2">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\DevExpress.Drawing.v22.2.dll</HintPath>
	  </Reference>
	  <Reference Include="DevExpress.Office.v22.2.Core">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\DevExpress.Office.v22.2.Core.dll</HintPath>
	  </Reference>
	  <Reference Include="DevExpress.Printing.v22.2.Core">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\DevExpress.Printing.v22.2.Core.dll</HintPath>
	  </Reference>
	  <Reference Include="DevExpress.Spreadsheet.v22.2.Core">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\DevExpress.Spreadsheet.v22.2.Core.dll</HintPath>
	  </Reference>
	  <Reference Include="DevExpress.Utils.v22.2">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\DevExpress.Utils.v22.2.dll</HintPath>
	  </Reference>
	  <Reference Include="DevExpress.XtraBars.v22.2">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\DevExpress.XtraBars.v22.2.dll</HintPath>
	  </Reference>
	  <Reference Include="DevExpress.XtraEditors.v22.2">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\DevExpress.XtraEditors.v22.2.dll</HintPath>
	  </Reference>
	  <Reference Include="DevExpress.XtraNavBar.v22.2">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\DevExpress.XtraNavBar.v22.2.dll</HintPath>
	  </Reference>
	  <Reference Include="DocumentFormat.OpenXml">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\DocumentFormat.OpenXml.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.Core">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.Core.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.Core.Controls">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.Core.Controls.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.Core.DocumentFormat">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.Core.DocumentFormat.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.Core.Rpc">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.Core.Rpc.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.ProPricer.Client">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.ProPricer.Client.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.ProPricer.Configuration">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.ProPricer.Configuration.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.ProPricer.EditionManager">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.ProPricer.EditionManager.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.ProPricer.ImportExport">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.ProPricer.ImportExport.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.ProPricer.Registration">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.ProPricer.Registration.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.ProPricer.Reports">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.ProPricer.Reports.dll</HintPath>
	  </Reference>
	  <Reference Include="EBS.Registration">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\EBS.Registration.dll</HintPath>
	  </Reference>
	  <Reference Include="NReco.Logging.File">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\NReco.Logging.File.dll</HintPath>
	  </Reference>
	  <Reference Include="PLUSManaged">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\PLUSManaged.dll</HintPath>
	  </Reference>
	  <Reference Include="System.IO.Packaging">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\System.IO.Packaging.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Windows.Forms">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\System.Windows.Forms.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Windows.Forms.Design">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\System.Windows.Forms.Design.dll</HintPath>
	  </Reference>
	  <Reference Include="System.Windows.Forms.Primitives">
		  <HintPath>..\_ProPricer Libraries\9_5_101_use\System.Windows.Forms.Primitives.dll</HintPath>
	  </Reference>
  </ItemGroup>

</Project>
