SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TempPPBurdenRates]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[TempPPBurdenRates];
END

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TempPPDirectRates]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[TempPPDirectRates];
END

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TempRates]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[TempRates];
END
GO

CREATE TABLE [dbo].[TempPPBurdenRates](
	[BurdenPool] [varchar](50) NOT NULL, 
	[Description] [varchar](1000) NOT NULL,
	[EffectiveDate] [varchar](50) NULL,
	[Date] [varchar](50) NOT NULL,
	[RC_Escal] [varchar](50) NULL,
	[R_Escal] [varchar](50) NULL,
	[RC_OH Dev] [varchar](50) NULL,
	[R_OH Dev] [varchar](50) NULL,
	[RC_OH Prod] [varchar](50) NULL,
	[R_OH Prod] [varchar](50) NULL,
	[RC_OH FBM] [varchar](50) NULL,
	[R_OH FBM] [varchar](50) NULL,
	[RC_OH LVS] [varchar](50) NULL,
	[R_OH LVS] [varchar](50) NULL,
	[RC_OH Hunts] [varchar](50) NULL,
	[R_OH Hunts] [varchar](50) NULL,
	[RC_OH Offsite] [varchar](50) NULL,
	[R_OH Offsite] [varchar](50) NULL,
	[RC_OH Michoud] [varchar](50) NULL,
	[R_OH Michoud] [varchar](50) NULL,
	[RC_OH Mich MH] [varchar](50) NULL,
	[R_OH Mich MH] [varchar](50) NULL,
	[RC_OH Prg Uni] [varchar](50) NULL,
	[R_OH Prg Uni] [varchar](50) NULL,
	[RC_OH Pro DIR] [varchar](50) NULL,
	[R_OH Pro DIR] [varchar](50) NULL,
	[RC_OH Pro MSC] [varchar](50) NULL,
	[R_OH Pro MSC] [varchar](50) NULL, --AA
	[RC_OH Pro Serv] [varchar](50) NULL,
	[R_OH Pro Serv] [varchar](50) NULL,
	[RC_OH On Serv] [varchar](50) NULL,
	[R_OH On Serv] [varchar](50) NULL,
	[RC_OH Off Serv] [varchar](50) NULL,
	[R_OH Off Serv] [varchar](50) NULL,
	[RC_OH PH4] [varchar](50) NULL,
	[R_OH PH4] [varchar](50) NULL,	
	[RC_OH PH5] [varchar](50) NULL,
	[R_OH PH5] [varchar](50) NULL,
	[RC_Fringe] [varchar](50) NULL,
	[R_Fringe] [varchar](50) NULL,
	[RC_Fringe T2] [varchar](50) NULL,
	[R_Fringe T2] [varchar](50) NULL,
	[RC_FRG Serv Corp] [varchar](50) NULL,
	[R_FRG Serv Corp] [varchar](50) NULL,
	[RC_FRG Serv LMOS] [varchar](50) NULL,
	[R_FRG Serv LMOS] [varchar](50) NULL,
	[RC_G&A] [varchar](50) NULL,
	[R_G&A] [varchar](50) NULL,
	[RC_G&A T2] [varchar](50) NULL,
	[R_G&A T2] [varchar](50) NULL,
	[RC_FCCOM Dev] [varchar](50) NULL,
	[R_FCCOM Dev] [varchar](50) NULL, --Z
	[RC_FCCOM Prod] [varchar](50) NULL,
	[R_FCCOM Prod] [varchar](50) NULL,
	[RC_FCCOM FBM] [varchar](50) NULL,
	[R_FCCOM FBM] [varchar](50) NULL,
	[RC_FCCOM LVS] [varchar](50) NULL,
	[R_FCCOM LVS] [varchar](50) NULL,
	[RC_FCCOM Hunt] [varchar](50) NULL,
	[R_FCCOM Hunt] [varchar](50) NULL,
	[RC_FCCOM Ofst] [varchar](50) NULL,
	[R_FCCOM Ofst] [varchar](50) NULL,
	[RC_FCCOM Mich] [varchar](50) NULL,
	[R_FCCOM Mich] [varchar](50) NULL,
	[RC_FCM Prg Un] [varchar](50) NULL,
	[R_FCM Prg Un] [varchar](50) NULL,
	[RC_FCCOM Proc] [varchar](50) NULL,
	[R_FCCOM Proc] [varchar](50) NULL,
	[RC_FCCOM ProM] [varchar](50) NULL,
	[R_FCCOM ProM] [varchar](50) NULL,
	[RC_FCCOM G&A] [varchar](50) NULL,
	[R_FCCOM G&A] [varchar](50) NULL,
	[RC_FCM T2 G&A] [varchar](50) NULL,
	[R_FCM T2 G&A] [varchar](50) NULL,
	[RC_FCCM IWTA] [varchar](50) NULL,
	[R_FCCM IWTA] [varchar](50) NULL,
	[RC_FCCM PH2] [varchar](50) NULL,
	[R_FCCM PH2] [varchar](50) NULL,
	[RC_FCCM PH3] [varchar](50) NULL,
	[R_FCCM PH3] [varchar](50) NULL,
	[RC_FCCM PH4] [varchar](50) NULL,
	[R_FCCM PH4] [varchar](50) NULL,
	[RC_Fee/Prft] [varchar](50) NULL,
	[R_Fee/Prft] [varchar](50) NULL,
	[InputSource] [int] NOT NULL	-- 0=BurdenRate, 1=BurdenRateCommercial, 2=BurdenRateServices
	) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TempPPDirectRates](
	[ResourceType] [nvarchar](50) NOT NULL,
	[StartDate] [nvarchar](50) NOT NULL,
	[EndDate] [nvarchar](50) NOT NULL,
	[Resource] [nvarchar](50) NOT NULL,
	[Description] [varchar](1000) NOT NULL,
	[ResourceClass] [varchar](50) NULL,
	[BurdenPool] [varchar](50) NOT NULL,
	[Calendar] [varchar](50) NULL,
	[RateType] [varchar](50) NOT NULL,
	[EffectiveDate] [varchar](50) NULL,
	[BaseRate] [decimal](18, 6) NULL,
	[Step] [int] NOT NULL,
	[Factor] [int] NOT NULL,
	[InputSource] [int] NOT NULL	-- 0=DirectRate, 1=DirectRateCommercial
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TempRates](
	[CategoryId] [int] NULL,		-- placeholder for new category Id
	[Revision] [varchar](50) NULL,
	[Category] [varchar](50) NULL,
	[RateDescription] [varchar](255) NULL,
	[Source] [varchar](50) NULL,
	[RateCode] [varchar](50) NOT NULL,
	[ProPricer] [varchar](50) NULL,
	[CobraRateDesc] [varchar](255) NULL,
	[CobraRateSet] [varchar](50) NULL,
	[Code1] [varchar](50) NULL,
	[ColI] [varchar](50) NULL,
	[Section] [varchar](50) NULL,
	[SectionTitle] [varchar](255) NULL,
	[ColL] [varchar](50) NULL,
	[ATDescription] [varchar](255) NULL,
	[DisplayColumn] [varchar](50) NULL,
	[PPException] [varchar](50) NULL,
	[PPExceptionDescription] [varchar](256) NULL,
	[PP0] [varchar](256) NULL,
	[PP1] [varchar](256) NULL,
	[PP2] [varchar](256) NULL,
	[PP3] [varchar](256) NULL,
	[PP4] [varchar](256) NULL,
	[PP5] [varchar](256) NULL,
	[PP6] [varchar](256) NULL,
	[PP7] [varchar](256) NULL,
	[PP8] [varchar](256) NULL,
	[PP9] [varchar](256) NULL,
	[ColAA] [varchar](50) NULL,
	[ColAB] [varchar](50) NULL,
	[RY2002] [decimal](18, 6) NULL,
	[RY2003] [decimal](18, 6) NULL,
	[RY2004] [decimal](18, 6) NULL,
	[RY2005] [decimal](18, 6) NULL,
	[RY2006] [decimal](18, 6) NULL,
	[RY2007] [decimal](18, 6) NULL,
	[RY2008] [decimal](18, 6) NULL,
	[RY2009] [decimal](18, 6) NULL,
	[RY2010] [decimal](18, 6) NULL,
	[RY2011] [decimal](18, 6) NULL,
	[ColAM] [decimal](18, 6) NULL,
	[ColAN] [decimal](18, 6) NULL,
	[RY2012] [decimal](18, 6) NULL,
	[RY2013] [decimal](18, 6) NULL,
	[RY2014] [decimal](18, 6) NULL,
	[RY2015] [decimal](18, 6) NULL,
	[RY2016] [decimal](18, 6) NULL,
	[RY2017] [decimal](18, 6) NULL,
	[RY2018] [decimal](18, 6) NULL,
	[RY2019] [decimal](18, 6) NULL,
	[RY2020] [decimal](18, 6) NULL,
	[RY2021] [decimal](18, 6) NULL,
	[RY2022] [decimal](18, 6) NULL,
	[RY2023] [decimal](18, 6) NULL,
	[RY2024] [decimal](18, 6) NULL,
	[RY2025] [decimal](18, 6) NULL,
	[RY2026] [decimal](18, 6) NULL,
	[RY2027] [decimal](18, 6) NULL,
	[RY2028] [decimal](18, 6) NULL,
	[RY2029] [decimal](18, 6) NULL,
	[RY2030] [decimal](18, 6) NULL,
	[RY2031] [decimal](18, 6) NULL,
	[RY2032] [decimal](18, 6) NULL,
	[RY2033] [decimal](18, 6) NULL,
	[RY2034] [decimal](18, 6) NULL,
	[RY2035] [decimal](18, 6) NULL,
	[RY2036] [decimal](18, 6) NULL,
	[RY2037] [decimal](18, 6) NULL,
	[RY2038] [decimal](18, 6) NULL,
	[RY2039] [decimal](18, 6) NULL,
	[RY2040] [decimal](18, 6) NULL
) ON [PRIMARY]
GO
