<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Configurations>Debug;Release;ReleaseTFSCore</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GenTRAC.Models.Standard\GenTRAC.Models.Standard.csproj" />
    <ProjectReference Include="..\IES.Core\IES.Core.csproj" />
  </ItemGroup>

</Project>
