<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Configurations>Debug;Release;ReleaseTFSCore</Configurations>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GenTRAC.Models.Standard\GenTRAC.Models.Standard.csproj" />
    <ProjectReference Include="..\IES.Common.Core\IES.Common.Core.csproj" />
  </ItemGroup>

</Project>
