EXEC [dbo].[UpdateDbVersion] @DbVersion = '1', @AppVersion = '2024.13'; 
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SkillMix]') AND type in (N'U')) 
BEGIN
	DECLARE @constraint_name nvarchar(128)
	DECLARE @sql nvarchar(max)
	-- Dynamically removes the default constraints tied to IsPercentLocked, as the DF constraints have inconsistent autogenerated names (e.g., 'DF_SkillMix_IsPerc_4AD51E11'). --
	SELECT @constraint_name = name FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'[dbo].[SkillMix]') AND name LIKE N'DF__SkillMix__IsPerc%';
	IF @constraint_name IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [dbo].[SkillMix] DROP CONSTRAINT ' + QUOTENAME(@constraint_name); EXEC sp_executesql @sql; 
	END
	-- Drop the FK Constraint before dropping the MOQTypeSelectionID FK column --
	IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SkillMix_MOQTypeSelection]') AND parent_object_id = OBJECT_ID(N'[dbo].[SkillMix]'))
	BEGIN
	    ALTER TABLE [dbo].[SkillMix] 
		DROP CONSTRAINT [FK_SkillMix_MOQTypeSelection];
	END
	-- Drop MOQTypeSelectionID column if it exists --
	IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[SkillMix]') AND name = N'MOQTypeSelectionID')
	BEGIN
	    ALTER TABLE [dbo].[SkillMix] 
		DROP COLUMN MOQTypeSelectionID;
	END
	-- Drop IsPercentLocked column if it exists. --
	IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[SkillMix]') AND name = N'IsPercentLocked')
	BEGIN
	    ALTER TABLE [dbo].[SkillMix] 
		DROP COLUMN IsPercentLocked;
	END
	-- Add IsUserInput Column if it exists --
	IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[SkillMix]') AND name = N'IsUserInput')
	BEGIN
	    ALTER TABLE [dbo].[SkillMix] 
		ADD IsUserInput bit NOT NULL DEFAULT 0;
	END
	-- Modify the ResourceNew column to be nullable --
	ALTER TABLE [dbo].[SkillMix] 
	ALTER COLUMN [ResourceNew] varchar(50) NULL; 
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[version].[SkillMix]') AND type in (N'U')) 
BEGIN 
	DECLARE @constraint_name nvarchar(128)
	DECLARE @sql nvarchar(max)
	-- Dynamically removes the default constraints tied to IsPercentLocked, as the DF constraints have inconsistent autogenerated names (e.g., 'DF_SkillMix_IsPerc_4AD51E11'). --
	SELECT @constraint_name = name FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'[version].[SkillMix]') AND name LIKE N'DF__SkillMix__IsPerc%';
	IF @constraint_name IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [version].[SkillMix] DROP CONSTRAINT ' + QUOTENAME(@constraint_name); EXEC sp_executesql @sql; 
	END
	-- Drop the FK Constraint before dropping the MOQTypeSelectionID FK column --
	IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SkillMix_MOQTypeSelection]') AND parent_object_id = OBJECT_ID(N'[dbo].[SkillMix]'))
	BEGIN
	    ALTER TABLE [dbo].[SkillMix] 
		DROP CONSTRAINT [FK_SkillMix_MOQTypeSelection];
	END
	-- Drop MOQTypeSelectionID column if it exists --
	IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[version].[SkillMix]') AND name = N'MOQTypeSelectionID')
	BEGIN
	    ALTER TABLE [version].[SkillMix] 
		DROP COLUMN MOQTypeSelectionID;
	END
	-- Drop IsPercentLocked column if it exists. --
	IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[version].[SkillMix]') AND name = N'IsPercentLocked')
	BEGIN
	    ALTER TABLE [version].[SkillMix] 
		DROP COLUMN IsPercentLocked;
	END
	-- Add IsUserInput Column if it exists --
	IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[version].[SkillMix]') AND name = N'IsUserInput')
	BEGIN
	    ALTER TABLE [version].[SkillMix] 
		ADD IsUserInput bit NOT NULL DEFAULT 0;
	END
	-- Modify the ResourceNew column to be nullable --
	ALTER TABLE [version].[SkillMix] 
	ALTER COLUMN [ResourceNew] varchar(50) NULL; 
END 
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CommonDisclosureSkillMix]') AND type in (N'U'))
BEGIN
	DECLARE @constraint_name nvarchar(128)
	DECLARE @sql nvarchar(max)
	-- Dynamically removes the default constraints tied to IsPercentLocked, as the DF constraints have inconsistent autogenerated names (e.g., 'DF_SkillMix_IsPerc_4AD51E11'). --
	SELECT @constraint_name = name FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'[dbo].[CommonDisclosureSkillMix]') AND name LIKE N'DF__CommonDis__IsPer%';
	IF @constraint_name IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [dbo].[CommonDisclosureSkillMix] DROP CONSTRAINT ' + QUOTENAME(@constraint_name); EXEC sp_executesql @sql; 
	END
	-- Drop the FK Constraint before dropping the MOQTypeSelectionID FK column --
	IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CommonDisclosureSkillMix_MOQTypeSelection]') AND parent_object_id = OBJECT_ID(N'[dbo].[CommonDisclosureSkillMix]'))
	BEGIN
	    ALTER TABLE [dbo].[CommonDisclosureSkillMix] 
		DROP CONSTRAINT [FK_CommonDisclosureSkillMix_MOQTypeSelection];
	END
	-- Drop MOQTypeSelectionID column if it exists --
    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[CommonDisclosureSkillMix]') AND name = N'MOQTypeSelectionID')
    BEGIN
        ALTER TABLE [dbo].[CommonDisclosureSkillMix] 
	    DROP COLUMN MOQTypeSelectionID;
    END
	-- Drop IsPercentLocked column if it exists. --
    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[CommonDisclosureSkillMix]') AND name = N'IsPercentLocked')
    BEGIN
        ALTER TABLE [dbo].[CommonDisclosureSkillMix] 
	    DROP COLUMN IsPercentLocked;
    END
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[version].[CommonDisclosureSkillMix]') AND type in (N'U'))
BEGIN
	DECLARE @constraint_name nvarchar(128)
	DECLARE @sql nvarchar(max)
	-- Dynamically removes the default constraints tied to IsPercentLocked, as the DF constraints have inconsistent autogenerated names (e.g., 'DF_SkillMix_IsPerc_4AD51E11'). --
	SELECT @constraint_name = name FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'[version].[CommonDisclosureSkillMix]') AND name LIKE N'DF__CommonDis__IsPer%';
	IF @constraint_name IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [version].[CommonDisclosureSkillMix] DROP CONSTRAINT ' + QUOTENAME(@constraint_name); EXEC sp_executesql @sql; 
	END
	-- Drop the FK Constraint before dropping the MOQTypeSelectionID FK column --
	IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[version].[FK_CommonDisclosureSkillMix_MOQTypeSelection]') AND parent_object_id = OBJECT_ID(N'[version].[CommonDisclosureSkillMix]'))
	BEGIN
	    ALTER TABLE [version].[CommonDisclosureSkillMix] 
		DROP CONSTRAINT [FK_CommonDisclosureSkillMix_MOQTypeSelection];
	END
	-- Drop MOQTypeSelectionID column if it exists --
    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[version].[CommonDisclosureSkillMix]') AND name = N'MOQTypeSelectionID')
    BEGIN
        ALTER TABLE [version].[CommonDisclosureSkillMix] 
	    DROP COLUMN MOQTypeSelectionID;
    END
	-- Drop IsPercentLocked column if it exists. --
    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[version].[CommonDisclosureSkillMix]') AND name = N'IsPercentLocked')
    BEGIN
        ALTER TABLE [version].[CommonDisclosureSkillMix] 
	    DROP COLUMN IsPercentLocked;
    END
END

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ReportLU]') AND type in (N'U')) 
BEGIN
	DELETE FROM dbo.ReportLU
		WHERE ReportName = 'Standard Reports';
END
GO

/*
	## START ##

	11/5/2024 [ranzalon] - SLMX_POLM_PROPH-2258 - Remove ProPricer Trip_ Fields
*/

IF EXISTS (SELECT 1 FROM [dbo].[ProPricerFieldLU] WHERE ProPricerField like 'Trip_%') 
BEGIN
	-- Set any selected Trip_ fields in existing Pro Pricer Exports to BLANK
	UPDATE [dbo].[ProPricerFieldXREF]
		SET ProPricerFieldID = 10 -- BLANK
		WHERE ProPricerFieldID IN (
			SELECT ProPricerFieldID
			FROM [dbo].[ProPricerFieldLU]
			WHERE ProPricerField like 'Trip_%'
		)

	-- Remove the field lookup values
	DELETE
	  FROM [dbo].[ProPricerFieldLU]
	  WHERE ProPricerField like 'Trip_%'
END
GO

/*
	11/5/2024 [ranzalon] - SLMX_POLM_PROPH-2258 - Remove ProPricer Trip_ Fields

	## END ##
*/