//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int ID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Name { get; set; }
        public byte[] Contents { get; set; }
        public string UploadedBy { get; set; }
        public int AttachmentType { get; set; }
        public int ProposalID { get; set; }
    
        public virtual Proposal Proposal { get; set; }
    }
}
