//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CannedResponsesPAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CannedResponsesPAR()
        {
            this.ProposalPARChecklistXREFs = new HashSet<ProposalPARChecklistXREF>();
        }
    
        public int CannedResponseId { get; set; }
        public string Text { get; set; }
        public int QuestionId { get; set; }
    
        public virtual PARChecklistContent PARChecklistContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalPARChecklistXREF> ProposalPARChecklistXREFs { get; set; }
    }
}
