//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataMartEmployee
    {
        public string empl_ser_no { get; set; }
        public string empl_first_nm { get; set; }
        public string empl_mi_nm { get; set; }
        public string empl_last_nm { get; set; }
        public string empl_gq_nm { get; set; }
        public string nt_account_nm { get; set; }
        public string empl_stat_cd { get; set; }
        public string work_st_cd { get; set; }
        public string work_city_nm { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string job_level { get; set; }
        public Nullable<byte> FLSAStatus { get; set; }
        public string rpt_to_ser_no { get; set; }
        public string nt_domain_nm { get; set; }
        public Nullable<double> empl_std_hrs { get; set; }
        public string work_st_nm { get; set; }
        public string work_country_cd { get; set; }
        public string work_country_nm { get; set; }
        public string OPERATING_CMPT_CD { get; set; }
        public string OPERATING_CMPT_DESC { get; set; }
        public string FORMAL_DESC { get; set; }
        public string TOP_TIER_OC_CD { get; set; }
        public string TOP_TIER_DESC { get; set; }
        public string BUS_AREA_DESC { get; set; }
        public string BUS_AREA_CD { get; set; }
        public string DEPT_SETID_NO { get; set; }
        public string BUS_AREA_SHORT_NM { get; set; }
        public string BUS_AREA_LONG_NM { get; set; }
    }
}
