//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARChecklistContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARChecklistContent()
        {
            this.ProposalPARChecklistXREFs = new HashSet<ProposalPARChecklistXREF>();
            this.CannedResponsesPARs = new HashSet<CannedResponsesPAR>();
        }
    
        public int PARChecklistContentID { get; set; }
        public string ChecklistText { get; set; }
        public int TextTypeID { get; set; }
        public int SortOrder { get; set; }
        public byte ColumnOrder { get; set; }
        public int ProposalAdequacyReviewID { get; set; }
        public string QuestionNumber { get; set; }
        public string Reference { get; set; }
        public string SubmissionItem { get; set; }
        public bool YesOnly { get; set; }
    
        public virtual ProposalAdequacyReview ProposalAdequacyReview { get; set; }
        public virtual TextTypeLU TextTypeLU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalPARChecklistXREF> ProposalPARChecklistXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CannedResponsesPAR> CannedResponsesPARs { get; set; }
    }
}
