//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalPricingReview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProposalPricingReview()
        {
            this.PPRChecklistContents = new HashSet<PPRChecklistContent>();
        }
    
        public int ProposalPricingReviewID { get; set; }
        public int ChecklistVersion { get; set; }
        public bool IsCurrent { get; set; }
        public Nullable<int> ProposalChecklistTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPRChecklistContent> PPRChecklistContents { get; set; }
        public virtual ProposalChecklistTypeLU ProposalChecklistTypeLU { get; set; }
    }
}
