//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalContractsData
    {
        public int ProposalContractsDataId { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int ProposalID { get; set; }
        public Nullable<int> PreviouslySubmittedROM { get; set; }
        public Nullable<System.DateTime> CustomerSubmittalDate { get; set; }
        public string ContractsCorrespondLogNumber { get; set; }
        public Nullable<long> FinalNegotiatedValue { get; set; }
        public Nullable<System.DateTime> FinalNegotiatedDate { get; set; }
        public Nullable<int> EppDelegationAuthority { get; set; }
        public string EppRosDelegationNotes { get; set; }
        public Nullable<bool> LmWon { get; set; }
        public Nullable<System.DateTime> ModCompletedDate { get; set; }
        public string CageCode { get; set; }
        public Nullable<System.DateTime> CustomerDueDate { get; set; }
        public Nullable<int> IsInsuranceDirect { get; set; }
        public Nullable<int> InsuranceType { get; set; }
        public Nullable<long> ProposedInsurance { get; set; }
        public Nullable<long> NegotiatedInsurance { get; set; }
        public Nullable<System.DateTime> PlannedProgramEppDate { get; set; }
        public Nullable<System.DateTime> PlannedLobEppDate { get; set; }
        public Nullable<System.DateTime> PlannedPreSpaceEppDate { get; set; }
        public Nullable<System.DateTime> PlannedSpaceEppDate { get; set; }
        public Nullable<System.DateTime> PlannedPreCorporateEppDate { get; set; }
        public Nullable<System.DateTime> PlannedCorporateEppDate { get; set; }
        public Nullable<System.DateTime> PlannedBidEppDate { get; set; }
        public Nullable<System.DateTime> PlannedMissionSegmentEppDate { get; set; }
        public Nullable<System.DateTime> ScheduledActualProgramEppDate { get; set; }
        public Nullable<System.DateTime> ScheduledActualLobEppDate { get; set; }
        public Nullable<System.DateTime> ScheduledActualPreSpaceEppDate { get; set; }
        public Nullable<System.DateTime> ScheduledActualSpaceEppDate { get; set; }
        public Nullable<System.DateTime> ScheduledActualPreCorporateEppDate { get; set; }
        public Nullable<System.DateTime> ScheduledActualCorporateEppDate { get; set; }
        public Nullable<System.DateTime> ScheduledActualBidEppDate { get; set; }
        public Nullable<System.DateTime> ScheduledActualMissionSegmentEppDate { get; set; }
    
        public virtual EppDelegationAuthorityLU EppDelegationAuthorityLU { get; set; }
        public virtual Proposal Proposal { get; set; }
        public virtual Proposal Proposal1 { get; set; }
        public virtual CageCode CageCode1 { get; set; }
        public virtual InsuranceTypeLU InsuranceTypeLU { get; set; }
    }
}
