//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalPPRChecklistXREF
    {
        public int ProposalID { get; set; }
        public int PPRChecklistContentID { get; set; }
        public int ResponseID { get; set; }
        public int ResponseTypeID { get; set; }
    
        public virtual PPRChecklistContent PPRChecklistContent { get; set; }
        public virtual Proposal Proposal { get; set; }
        public virtual ResponseLU ResponseLU { get; set; }
        public virtual ResponseTypeLU ResponseTypeLU { get; set; }
    }
}
