//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalPARChecklistXREF
    {
        public int ProposalID { get; set; }
        public int PARChecklistContentID { get; set; }
        public int ResponseID { get; set; }
        public int ResponseTypeID { get; set; }
        public string Comment { get; set; }
        public string PageNumber { get; set; }
        public Nullable<int> CannedResponseId { get; set; }
    
        public virtual PARChecklistContent PARChecklistContent { get; set; }
        public virtual ResponseLU ResponseLU { get; set; }
        public virtual ResponseTypeLU ResponseTypeLU { get; set; }
        public virtual CannedResponsesPAR CannedResponsesPAR { get; set; }
        public virtual Proposal Proposal { get; set; }
    }
}
