//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalChecklist
    {
        public int ProposalChecklistID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int ProposalID { get; set; }
        public Nullable<System.DateTime> ProposalSubmittalDate { get; set; }
        public Nullable<long> ISGSTotalPrice { get; set; }
        public Nullable<long> ProfitFeeWithCom { get; set; }
        public Nullable<decimal> ROSPercentage { get; set; }
        public Nullable<decimal> LMLaborHours { get; set; }
        public Nullable<long> LMLaborCost { get; set; }
        public Nullable<long> SubcontractorCost { get; set; }
        public Nullable<long> MaterialCost { get; set; }
        public Nullable<long> IWTACost { get; set; }
        public Nullable<long> TravelCost { get; set; }
        public Nullable<long> OtherDirectCost { get; set; }
        public bool DeliverChecklistDFARS { get; set; }
        public Nullable<long> AbsoluteValue { get; set; }
        public Nullable<long> Com { get; set; }
        public Nullable<long> Profit { get; set; }
        public Nullable<long> CostThroughCom { get; set; }
        public Nullable<bool> IncludeInternationalCosts { get; set; }
    
        public virtual Proposal Proposal { get; set; }
    }
}
