//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalContractsData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProposalContractsData()
        {
            this.ProposalContractsOffers = new HashSet<ProposalContractsOffer>();
        }
    
        public int ProposalContractsDataId { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int PreviouslySubmittedROM { get; set; }
        public Nullable<System.DateTime> CustomerSubmittalDate { get; set; }
        public string ContractsCorrespondLogNumber { get; set; }
        public Nullable<long> FinalNegotiatedValue { get; set; }
        public Nullable<System.DateTime> FinalNegotiatedDate { get; set; }
        public int ProposalID { get; set; }
    
        public virtual Proposal Proposal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalContractsOffer> ProposalContractsOffers { get; set; }
        public virtual Proposal Proposal1 { get; set; }
    }
}
