//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalsAttachment
    {
        public int ProposalId { get; set; }
        public int AttachmentId { get; set; }
        public int AttachmentType { get; set; }
        public bool IsRevisionReference { get; set; }
    
        public virtual Proposal Proposal { get; set; }
        public virtual Attachment Attachment { get; set; }
        public virtual AttachmentTypeLU AttachmentTypeLU { get; set; }
    }
}
