//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseTypeLU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResponseTypeLU()
        {
            this.ProposalChecklistCompletes = new HashSet<ProposalChecklistComplete>();
            this.ProposalPARChecklistXREFs = new HashSet<ProposalPARChecklistXREF>();
            this.ProposalPPRChecklistXREFs = new HashSet<ProposalPPRChecklistXREF>();
        }
    
        public int ResponseTypeID { get; set; }
        public string ResponseType { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalChecklistComplete> ProposalChecklistCompletes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalPARChecklistXREF> ProposalPARChecklistXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalPPRChecklistXREF> ProposalPPRChecklistXREFs { get; set; }
    }
}
