//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenTRAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextTypeLU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TextTypeLU()
        {
            this.PARChecklistContents = new HashSet<PARChecklistContent>();
            this.PPRChecklistContents = new HashSet<PPRChecklistContent>();
        }
    
        public int TextTypeID { get; set; }
        public string TextType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARChecklistContent> PARChecklistContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPRChecklistContent> PPRChecklistContents { get; set; }
    }
}
