//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.MSTMetricModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BI_Datamart_PMMEntities : DbContext
    {
        public BI_Datamart_PMMEntities()
            : base("name=BI_Datamart_PMMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vw_BOE_Data> vw_BOE_Data { get; set; }
        public virtual DbSet<vw_BOE_Definition> vw_BOE_Definition { get; set; }
    }
}
