//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.MSTMetricModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BOE_Data
    {
        public int BOE_Data_ID { get; set; }
        public int PMM_Program_ID { get; set; }
        public string Program_Name { get; set; }
        public Nullable<int> Scope_ID { get; set; }
        public string Scope_Name { get; set; }
        public int BOE_Definition_ID { get; set; }
        public string Measure_Name { get; set; }
        public string Meas_Group { get; set; }
        public string Meas_Category { get; set; }
        public string Measure_Qualifier { get; set; }
        public string Function_Acronym { get; set; }
        public string Function_Description { get; set; }
        public Nullable<decimal> Measure_Data { get; set; }
        public Nullable<decimal> BaseMeas1_Data { get; set; }
        public Nullable<decimal> BaseMeas2_Data { get; set; }
        public Nullable<decimal> BaseMeas3_Data { get; set; }
        public Nullable<decimal> BaseMeas4_Data { get; set; }
        public Nullable<decimal> BaseMeas5_Data { get; set; }
        public string Program_LongName { get; set; }
        public string Program_Description { get; set; }
        public string Contract_Number { get; set; }
        public string Work_Packages { get; set; }
        public Nullable<System.DateTime> Measure_Start_Date { get; set; }
        public Nullable<System.DateTime> Measure_End_Date { get; set; }
        public Nullable<System.DateTime> Validated_Date { get; set; }
        public string Validated_By { get; set; }
        public string Cust_Approved { get; set; }
        public string Comment { get; set; }
        public string URL { get; set; }
        public string Data_Source { get; set; }
        public string Business_Area { get; set; }
        public string LOB { get; set; }
        public System.DateTime Date_Added { get; set; }
        public System.DateTime Date_Modified { get; set; }
        public string Modified_By { get; set; }
        public int Data_Source_ID { get; set; }
    }
}
