//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.MSTMetricModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BOE_Definition
    {
        public int BOE_Definition_ID { get; set; }
        public string Measure_Name { get; set; }
        public string Meas_Group { get; set; }
        public string Meas_Category { get; set; }
        public string Equation { get; set; }
        public string Units { get; set; }
        public string BaseMeas1_Name { get; set; }
        public string BaseMeas2_Name { get; set; }
        public string BaseMeas3_Name { get; set; }
        public string BaseMeas4_Name { get; set; }
        public string BaseMeas5_Name { get; set; }
        public string Meas_Description { get; set; }
        public System.DateTime Date_Added { get; set; }
        public System.DateTime Date_Modified { get; set; }
        public string Modified_By { get; set; }
    }
}
