<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IES.Models.Standard\IES.Models.Standard.csproj" />
    <ProjectReference Include="..\IES.Standard\IES.Standard.csproj" />
  </ItemGroup>

</Project>
