//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOE()
        {
            this.BOEApprovals = new HashSet<BOEApproval>();
            this.BOEApprovalHistories = new HashSet<BOEApprovalHistory>();
            this.BOEComments = new HashSet<BOEComment>();
            this.BOECommentHistories = new HashSet<BOECommentHistory>();
            this.BOECustomFieldValueXREFs = new HashSet<BOECustomFieldValueXREF>();
            this.BOEStateHistories = new HashSet<BOEStateHistory>();
            this.BOETaskElements = new HashSet<BOETaskElement>();
            this.BOEUserRoles = new HashSet<BOEUserRole>();
            this.BOEUserRoleHistories = new HashSet<BOEUserRoleHistory>();
            this.MaterialTaskElements = new HashSet<MaterialTaskElement>();
            this.ODCTaskElements = new HashSet<ODCTaskElement>();
            this.SumOfBOE_OrdinaryVariableXREF = new HashSet<SumOfBOE_OrdinaryVariableXREF>();
            this.SumOfBOE_WorkspaceVariableXREF = new HashSet<SumOfBOE_WorkspaceVariableXREF>();
            this.TravelTripTaskElements = new HashSet<TravelTripTaskElement>();
            this.WBS_CLIN_BOE_XREF = new HashSet<WBS_CLIN_BOE_XREF>();
            this.RteTemplateAnswers = new HashSet<RteTemplateAnswer>();
        }
    
        public int BOEID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int BOEStateID { get; set; }
        public System.DateTime BOEStartDate { get; set; }
        public System.DateTime BOEEndDate { get; set; }
        public string BOEDescription { get; set; }
        public string DataSource { get; set; }
        public int WorkspaceID { get; set; }
        public bool MetricDisclosureAcknowledge { get; set; }
        public int NumAuthorReassigned { get; set; }
        public bool IsMaterial { get; set; }
        public string BOETitle { get; set; }
        public bool IsMultiClinWbs { get; set; }
    
        public virtual BOEStateLU BOEStateLU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOEApproval> BOEApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOEApprovalHistory> BOEApprovalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOEComment> BOEComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOECommentHistory> BOECommentHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOECustomFieldValueXREF> BOECustomFieldValueXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOEStateHistory> BOEStateHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOETaskElement> BOETaskElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOEUserRole> BOEUserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOEUserRoleHistory> BOEUserRoleHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialTaskElement> MaterialTaskElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODCTaskElement> ODCTaskElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SumOfBOE_OrdinaryVariableXREF> SumOfBOE_OrdinaryVariableXREF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SumOfBOE_WorkspaceVariableXREF> SumOfBOE_WorkspaceVariableXREF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelTripTaskElement> TravelTripTaskElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WBS_CLIN_BOE_XREF> WBS_CLIN_BOE_XREF { get; set; }
        public virtual Workspace Workspace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RteTemplateAnswer> RteTemplateAnswers { get; set; }
    }
}
