//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOEApprovalHistory
    {
        public int BOEApprovalHistoryID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int BOEID { get; set; }
        public string Approval { get; set; }
        public int ApprovalETIUserID { get; set; }
    
        public virtual BOE BOE { get; set; }
        public virtual ETIuser ETIuser { get; set; }
    }
}
