//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOECopyMetric
    {
        public Nullable<int> SourceBOEID { get; set; }
        public Nullable<int> TargetBOEID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
