//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOEComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOEComment()
        {
            this.BOEComment1 = new HashSet<BOEComment>();
            this.BOECommentHistories = new HashSet<BOECommentHistory>();
        }
    
        public int BOECommentID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int FieldID { get; set; }
        public string BOEComments { get; set; }
        public int BOECommentETIUserID { get; set; }
        public Nullable<int> BOEResponseToCommentID { get; set; }
        public int BOEID { get; set; }
    
        public virtual BOE BOE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOEComment> BOEComment1 { get; set; }
        public virtual BOEComment BOEComment2 { get; set; }
        public virtual ETIuser ETIuser { get; set; }
        public virtual FieldLU FieldLU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOECommentHistory> BOECommentHistories { get; set; }
    }
}
