//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOECommentHistory
    {
        public int BOECommentHistoryID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int BOECommentID { get; set; }
        public int BOEID { get; set; }
        public int FieldID { get; set; }
        public string CurrentComment { get; set; }
        public string UpdatedComment { get; set; }
        public int ChangedByETIUserID { get; set; }
    
        public virtual BOEComment BOEComment { get; set; }
        public virtual ETIuser ETIuser { get; set; }
        public virtual FieldLU FieldLU { get; set; }
        public virtual BOE BOE { get; set; }
    }
}
