//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOEFormPBOEResourcesXREF
    {
        public int PBOEFormID { get; set; }
        public int ResourceID { get; set; }
    
        public virtual Resource Resource { get; set; }
    }
}
