//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOEFormIBOE
    {
        public int IBOEFormID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int WorkspaceID { get; set; }
        public string FormName { get; set; }
        public string Description { get; set; }
        public string BasisAndRationale { get; set; }
        public string ProposalTitle { get; set; }
        public string ProposalDate { get; set; }
        public string Poc { get; set; }
        public string PocPhone { get; set; }
        public string Approver { get; set; }
        public string ApproverPhone { get; set; }
        public string BusinessArea { get; set; }
        public int Revision { get; set; }
        public int FormVersion { get; set; }
    }
}
