//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOELaborSpread
    {
        public int BOELaborSpreadID { get; set; }
        public int BOELaborTypeID { get; set; }
        public System.DateTime LaborSpreadDate { get; set; }
        public Nullable<decimal> LaborSpreadValue { get; set; }
    
        public virtual BOELaborType BOELaborType { get; set; }
    }
}
