//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOELaborType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOELaborType()
        {
            this.BOELaborSpreads = new HashSet<BOELaborSpread>();
            this.BOELaborTypeCustomFieldValueXREFs = new HashSet<BOELaborTypeCustomFieldValueXREF>();
        }
    
        public int BOELaborTypeID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<int> PerformingOrganizationID { get; set; }
        public System.DateTime BOELaborTypeStartDate { get; set; }
        public System.DateTime BOELaborTypeEndDate { get; set; }
        public int SpreadCurveID { get; set; }
        public Nullable<decimal> PercentSpread { get; set; }
        public Nullable<decimal> ValueSpread { get; set; }
        public int BOETaskElementID { get; set; }
        public Nullable<int> SpreadTypeID { get; set; }
        public bool PercentSpreadLocked { get; set; }
        public bool HourSpreadLocked { get; set; }
        public Nullable<int> WBSID { get; set; }
        public Nullable<int> CLINID { get; set; }
        public Nullable<bool> CanOffload { get; set; }
        public int LaborSortId { get; set; }
        public Nullable<int> MOQTypeSelectionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOELaborSpread> BOELaborSpreads { get; set; }
        public virtual BOETaskElement BOETaskElement { get; set; }
        public virtual CLIN CLIN { get; set; }
        public virtual PerformingOrganization PerformingOrganization { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual SpreadCurveLU SpreadCurveLU { get; set; }
        public virtual SpreadTypeLU SpreadTypeLU { get; set; }
        public virtual WorkBreakdownStructure WorkBreakdownStructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOELaborTypeCustomFieldValueXREF> BOELaborTypeCustomFieldValueXREFs { get; set; }
        public virtual MOQTypeLU MOQTypeSelection { get; set; }
    }
}
