//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOEStateHistory
    {
        public int BOEStateHistoryID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int BOEID { get; set; }
        public int FieldID { get; set; }
        public int CurrentBOEStateID { get; set; }
        public int UpdatedBOEStateID { get; set; }
        public int ChangedByETIUserID { get; set; }
    
        public virtual BOEStateLU BOEStateLU { get; set; }
        public virtual BOEStateLU BOEStateLU1 { get; set; }
        public virtual ETIuser ETIuser { get; set; }
        public virtual FieldLU FieldLU { get; set; }
        public virtual BOE BOE { get; set; }
    }
}
