//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOETaskElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOETaskElement()
        {
            this.BOELaborTypes = new HashSet<BOELaborType>();
            this.MOQTypeSelections = new HashSet<MOQTypeSelection>();
            this.BOETaskElementCustomFieldValueXREFs = new HashSet<BOETaskElementCustomFieldValueXREF>();
            this.BOETaskElementWorkspaceVariableXREFs = new HashSet<BOETaskElementWorkspaceVariableXREF>();
            this.MOQTypeSelectionTableDataResourceHours = new HashSet<MOQTypeSelectionTableDataResourceHour>();
            this.OrdinaryVariables = new HashSet<OrdinaryVariable>();
            this.RteTemplateAnswers = new HashSet<RteTemplateAnswer>();
            this.CommonDisclosureSkillMixes = new HashSet<CommonDisclosureSkillMix>();
            this.SkillMixes = new HashSet<SkillMix>();
        }
    
        public int BOETaskElementID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public string TaskID { get; set; }
        public string TaskTitle { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        public Nullable<System.DateTime> TaskEndDate { get; set; }
        public string MOQHoursEquation { get; set; }
        public string MOQCostEquation { get; set; }
        public string MOQText { get; set; }
        public Nullable<int> MOQTypeID { get; set; }
        public int BOEID { get; set; }
        public bool LaborTypeWarningFlag { get; set; }
        public string IMS_ID { get; set; }
        public int TaskElementTypeID { get; set; }
        public int SortOrderID { get; set; }
    
        public virtual BOE BOE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOELaborType> BOELaborTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOQTypeSelection> MOQTypeSelections { get; set; }
        public virtual MOQTypeLU MOQTypeLU { get; set; }
        public virtual TaskElementTypeLU TaskElementTypeLU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOETaskElementCustomFieldValueXREF> BOETaskElementCustomFieldValueXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOETaskElementWorkspaceVariableXREF> BOETaskElementWorkspaceVariableXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOQTypeSelectionTableDataResourceHour> MOQTypeSelectionTableDataResourceHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdinaryVariable> OrdinaryVariables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RteTemplateAnswer> RteTemplateAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonDisclosureSkillMix> CommonDisclosureSkillMixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillMix> SkillMixes { get; set; }
    }
}
