//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOETaskElementCustomFieldValueXREF
    {
        public int BTECFVID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int BOETaskElementID { get; set; }
        public int CustomFieldValueID { get; set; }
    
        public virtual CustomFieldValue CustomFieldValue { get; set; }
        public virtual BOETaskElement BOETaskElement { get; set; }
    }
}
