//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomFieldValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomFieldValue()
        {
            this.BOECustomFieldValueXREFs = new HashSet<BOECustomFieldValueXREF>();
            this.BOELaborTypeCustomFieldValueXREFs = new HashSet<BOELaborTypeCustomFieldValueXREF>();
            this.BOETaskElementCustomFieldValueXREFs = new HashSet<BOETaskElementCustomFieldValueXREF>();
            this.MSTTravelTripCustomFieldValueXREFs = new HashSet<MSTTravelTripCustomFieldValueXREF>();
            this.TravelTripCustomFieldValueXREFs = new HashSet<TravelTripCustomFieldValueXREF>();
            this.TravelTripTaskElementCustomFieldValueXREFs = new HashSet<TravelTripTaskElementCustomFieldValueXREF>();
        }
    
        public int CustomFieldValueID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public string CustomFieldValueName { get; set; }
        public string CustomFieldValueDescription { get; set; }
        public int CustomFieldID { get; set; }
        public bool CustomFieldValueInUseFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOECustomFieldValueXREF> BOECustomFieldValueXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOELaborTypeCustomFieldValueXREF> BOELaborTypeCustomFieldValueXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOETaskElementCustomFieldValueXREF> BOETaskElementCustomFieldValueXREFs { get; set; }
        public virtual CustomField CustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTTravelTripCustomFieldValueXREF> MSTTravelTripCustomFieldValueXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelTripCustomFieldValueXREF> TravelTripCustomFieldValueXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelTripTaskElementCustomFieldValueXREF> TravelTripTaskElementCustomFieldValueXREFs { get; set; }
    }
}
