//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetricDetail()
        {
            this.BOETaskElementMetricDetailXREFs = new HashSet<BOETaskElementMetricDetailXREF>();
        }
    
        public int MetricDetailID { get; set; }
        public int SourceSystemID { get; set; }
        public string ProgramName { get; set; }
        public string ScopeName { get; set; }
        public Nullable<decimal> MeasureData { get; set; }
        public string MeasureName { get; set; }
        public string DataSource { get; set; }
        public string MeasureFunction { get; set; }
        public string Equation { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ContractNumber { get; set; }
        public string WorkPackages { get; set; }
        public string BaseMeasure1Name { get; set; }
        public Nullable<decimal> BaseMeasure1Data { get; set; }
        public int ProgramID { get; set; }
        public string MeasureFunctionID { get; set; }
        public int DataSourceID { get; set; }
        public int MeasureID { get; set; }
        public string MeasureQualifier { get; set; }
        public string BaseMeasure2Name { get; set; }
        public Nullable<decimal> BaseMeasure2Data { get; set; }
        public string BaseMeasure3Name { get; set; }
        public Nullable<decimal> BaseMeasure3Data { get; set; }
        public string BaseMeasure4Name { get; set; }
        public Nullable<decimal> BaseMeasure4Data { get; set; }
        public string BaseMeasure5Name { get; set; }
        public Nullable<decimal> BaseMeasure5Data { get; set; }
        public string BusinessArea { get; set; }
        public string LineOfBusiness { get; set; }
        public string MeasureGroupName { get; set; }
        public string MeasureCategoryName { get; set; }
        public string MeasureDescription { get; set; }
        public string MeasureLink { get; set; }
        public Nullable<System.DateTime> MeasureValidationDate { get; set; }
        public string MeasureValidatedBy { get; set; }
        public string ProgramDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOETaskElementMetricDetailXREF> BOETaskElementMetricDetailXREFs { get; set; }
    }
}
