//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOQTypeSelectionTableDataResourceHour
    {
        public int MOQTypeSelectionTableDataResourceHoursId { get; set; }
        public string ResourceName { get; set; }
        public decimal WbsHours { get; set; }
        public decimal TotalHours { get; set; }
        public int MOQTypeSelectionTableDataId { get; set; }
        public int BOETaskElementID { get; set; }
        public int BOEID { get; set; }
        public string BRCName { get; set; }
    
        public virtual MOQTypeSelectionTableData MOQTypeSelectionTableData { get; set; }
        public virtual BOE BOE { get; set; }
        public virtual BOETaskElement BOETaskElement { get; set; }
    }
}
