//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTTravelNonzoneFeesAndCost
    {
        public int FeesAndCostsID { get; set; }
        public int ModeID { get; set; }
        public decimal TravelAgencyFee { get; set; }
        public decimal MiscOther { get; set; }
        public System.DateTime UpdateDT { get; set; }
    
        public virtual MSTTravelModeLU MSTTravelModeLU { get; set; }
    }
}
