//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTZoneTravelResource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTZoneTravelResource()
        {
            this.MSTTravelTrips = new HashSet<MSTTravelTrip>();
        }
    
        public int ResourceID { get; set; }
        public string Resource { get; set; }
        public int Zone { get; set; }
        public bool isAirfare { get; set; }
        public int OriginID { get; set; }
        public string LookupValue { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTTravelTrip> MSTTravelTrips { get; set; }
        public virtual MSTZoneTravelOrigin MSTZoneTravelOrigin { get; set; }
    }
}
