//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODCSpread
    {
        public int ODCSpreadID { get; set; }
        public System.DateTime ODCSpreadDate { get; set; }
        public long ODCSpreadValue { get; set; }
        public int ODCTypeID { get; set; }
    
        public virtual ODCType ODCType { get; set; }
    }
}
