//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODCType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ODCType()
        {
            this.ODCSpreads = new HashSet<ODCSpread>();
        }
    
        public int ODCTypeID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<int> PerformingOrganizationID { get; set; }
        public System.DateTime ODCTypeStartDate { get; set; }
        public Nullable<System.DateTime> ODCTypeEndDate { get; set; }
        public int SpreadCurveID { get; set; }
        public Nullable<decimal> ODCTypeCost { get; set; }
        public int ODCTaskElementID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODCSpread> ODCSpreads { get; set; }
        public virtual ODCTaskElement ODCTaskElement { get; set; }
        public virtual PerformingOrganization PerformingOrganization { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual SpreadCurveLU SpreadCurveLU { get; set; }
    }
}
