//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdinaryVariableSumVariableResourceTypeXREF
    {
        public int OVSVRTID { get; set; }
        public int OrdinaryVariableID { get; set; }
        public int SumVariableResourceTypeID { get; set; }
    
        public virtual OrdinaryVariable OrdinaryVariable { get; set; }
        public virtual SumVariableResourceTypeLU SumVariableResourceTypeLU { get; set; }
    }
}
