//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformingOrganization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PerformingOrganization()
        {
            this.MSTTravelTrips = new HashSet<MSTTravelTrip>();
            this.ODCTypes = new HashSet<ODCType>();
            this.TravelTrips = new HashSet<TravelTrip>();
            this.WorkspacePerformingOrganizations = new HashSet<WorkspacePerformingOrganization>();
            this.BOELaborTypes = new HashSet<BOELaborType>();
        }
    
        public int PerformingOrganizationID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public string PerformingOrganizationName { get; set; }
        public string PerformingOrganizationDescription { get; set; }
        public int PerformingOrganizationListID { get; set; }
        public bool DeletedFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTTravelTrip> MSTTravelTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODCType> ODCTypes { get; set; }
        public virtual PerformingOrganizationList PerformingOrganizationList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelTrip> TravelTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkspacePerformingOrganization> WorkspacePerformingOrganizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOELaborType> BOELaborTypes { get; set; }
    }
}
