//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMapSpread
    {
        public int ID { get; set; }
        public int WorkspaceId { get; set; }
        public int ProjectMapId { get; set; }
        public System.DateTime SpreadDate { get; set; }
        public decimal SpreadValue { get; set; }
    
        public virtual ProjectMap ProjectMap { get; set; }
    }
}
