//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProPricerTypeLU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProPricerTypeLU()
        {
            this.ProPricerCustomFieldXREFs = new HashSet<ProPricerCustomFieldXREF>();
            this.ProPricerFieldLUs = new HashSet<ProPricerFieldLU>();
            this.ProPricerFieldXREFs = new HashSet<ProPricerFieldXREF>();
            this.SystemProPricerCustomFieldXREFs = new HashSet<SystemProPricerCustomFieldXREF>();
            this.SystemProPricerFieldXREFs = new HashSet<SystemProPricerFieldXREF>();
        }
    
        public int ProPricerTypeID { get; set; }
        public string ProPricerType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProPricerCustomFieldXREF> ProPricerCustomFieldXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProPricerFieldLU> ProPricerFieldLUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProPricerFieldXREF> ProPricerFieldXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemProPricerCustomFieldXREF> SystemProPricerCustomFieldXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemProPricerFieldXREF> SystemProPricerFieldXREFs { get; set; }
    }
}
