//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RteTemplateAnswer
    {
        public int AnswerID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int QuestionID { get; set; }
        public int BOEID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string Text { get; set; }
        public int RteTemplateSourceId { get; set; }
    
        public virtual BOE BOE { get; set; }
        public virtual BOETaskElement BOETaskElement { get; set; }
        public virtual RteTemplateQuestion RteTemplateQuestion { get; set; }
    }
}
