//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillMix
    {
        public int SkillMixID { get; set; }
        public string Rationale { get; set; }
        public Nullable<bool> Included { get; set; }
        public Nullable<decimal> ProposedHours { get; set; }
        public Nullable<decimal> HistoricalHours { get; set; }
        public Nullable<decimal> BOESkillMix { get; set; }
        public Nullable<decimal> LaborSkillMix { get; set; }
        public string ResourceOld { get; set; }
        public string ResourceNew { get; set; }
        public Nullable<int> BOEID { get; set; }
        public Nullable<int> BOETaskElementID { get; set; }
        public Nullable<int> MOQTypeSelectionID { get; set; }
    
        public virtual BOE BOE { get; set; }
        public virtual BOETaskElement BOETaskElement { get; set; }
        public virtual MOQTypeSelection MOQTypeSelection { get; set; }
    }
}
