//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillMix
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SkillMix()
        {
            this.CommonDisclosureSkillMixes = new HashSet<CommonDisclosureSkillMix>();
        }
    
        public int SkillMixID { get; set; }
        public string Rationale { get; set; }
        public Nullable<bool> Included { get; set; }
        public decimal ProposedHours { get; set; }
        public decimal HistoricalHours { get; set; }
        public decimal BOESkillMix { get; set; }
        public decimal LaborSkillMix { get; set; }
        public string ResourceOld { get; set; }
        public string ResourceNew { get; set; }
        public int BOEID { get; set; }
        public int BOETaskElementID { get; set; }
        public int MOQTypeSelectionID { get; set; }
    
        public virtual BOE BOE { get; set; }
        public virtual BOETaskElement BOETaskElement { get; set; }
        public virtual MOQTypeSelection MOQTypeSelection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonDisclosureSkillMix> CommonDisclosureSkillMixes { get; set; }
    }
}
