//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillMixSummary
    {
        public int SkillMixSummaryID { get; set; }
        public string Rationale { get; set; }
        public bool Included { get; set; }
        public decimal ProposedLegacyResource { get; set; }
        public decimal HistoricalHours { get; set; }
        public decimal ResourceHours { get; set; }
        public decimal ProposedBrc { get; set; }
        public decimal ProposedSkillMix { get; set; }
        public decimal HistoricalSkillMix { get; set; }
        public string ResourceID { get; set; }
        public string BusinessResourceID { get; set; }
        public int BOEID { get; set; }
        public int BOETaskElementID { get; set; }
        public bool IsUserInput { get; set; }
    
        public virtual BOE BOE { get; set; }
        public virtual BOETaskElement BOETaskElement { get; set; }
    }
}
