//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SumOfBOE_WorkspaceVariableXREF
    {
        public long WVSumID { get; set; }
        public int WorkspaceVariableID { get; set; }
        public Nullable<int> CLINID { get; set; }
        public Nullable<int> WBSID { get; set; }
        public Nullable<int> BOEID { get; set; }
    
        public virtual CLIN CLIN { get; set; }
        public virtual WorkBreakdownStructure WorkBreakdownStructure { get; set; }
        public virtual WorkspaceVariable WorkspaceVariable { get; set; }
        public virtual BOE BOE { get; set; }
    }
}
