//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SumVariableResourceTypeLU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SumVariableResourceTypeLU()
        {
            this.OrdinaryVariableSumVariableResourceTypeXREFs = new HashSet<OrdinaryVariableSumVariableResourceTypeXREF>();
            this.WorkspaceVariableSumVariableResourceTypeXREFs = new HashSet<WorkspaceVariableSumVariableResourceTypeXREF>();
        }
    
        public int SumVariableResourceTypeID { get; set; }
        public string SumVariableResourceType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdinaryVariableSumVariableResourceTypeXREF> OrdinaryVariableSumVariableResourceTypeXREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkspaceVariableSumVariableResourceTypeXREF> WorkspaceVariableSumVariableResourceTypeXREFs { get; set; }
    }
}
