//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemProPricerCustomFieldXREF
    {
        public int PCID { get; set; }
        public int SystemProPricerExportID { get; set; }
        public string CustomField { get; set; }
        public int ProPricerTypeID { get; set; }
        public int ProPricerCustomFieldSelectionID { get; set; }
        public byte ListOrder { get; set; }
    
        public virtual ProPricerCustomFieldSelectionLU ProPricerCustomFieldSelectionLU { get; set; }
        public virtual ProPricerTypeLU ProPricerTypeLU { get; set; }
        public virtual SystemProPricerExport SystemProPricerExport { get; set; }
    }
}
