//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserRole
    {
        public int SystemUserRoleID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int ETIUserID { get; set; }
        public int RoleID { get; set; }
    
        public virtual ETIuser ETIuser { get; set; }
        public virtual RoleLU RoleLU { get; set; }
    }
}
