//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemOffloadRate
    {
        public int OffloadRateID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public string Resource { get; set; }
        public string PerfOrg { get; set; }
        public decimal PercentToOffload { get; set; }
        public int Year { get; set; }
        public string SubcontractorResource { get; set; }
        public decimal HourlyRate { get; set; }
    }
}
