//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMResourceRate
    {
        public int TMResourceRateID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int WorkspaceID { get; set; }
        public int TMResourceID { get; set; }
        public Nullable<System.DateTime> TMResourceRateStartDate { get; set; }
        public Nullable<System.DateTime> TMResourceRateEndDate { get; set; }
        public Nullable<decimal> TMResourceRate1 { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual Workspace Workspace { get; set; }
    }
}
