//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelTrip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelTrip()
        {
            this.TravelTripCustomFieldValueXREFs = new HashSet<TravelTripCustomFieldValueXREF>();
        }
    
        public int TravelTripID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public Nullable<int> GroupID { get; set; }
        public int SegmentID { get; set; }
        public int PerformingOrganizationID { get; set; }
        public int TripID { get; set; }
        public System.DateTime TripDate { get; set; }
        public int NumTrips { get; set; }
        public int NumPeople { get; set; }
        public int NumDays { get; set; }
        public string Purpose { get; set; }
        public int TravelTripTaskElementID { get; set; }
        public Nullable<System.DateTime> TripLockedDT { get; set; }
    
        public virtual PerformingOrganization PerformingOrganization { get; set; }
        public virtual TravelTripTaskElement TravelTripTaskElement { get; set; }
        public virtual Trip Trip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelTripCustomFieldValueXREF> TravelTripCustomFieldValueXREFs { get; set; }
        public virtual SegmentLU SegmentLU { get; set; }
    }
}
