//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelTripTaskElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelTripTaskElement()
        {
            this.MSTTravelTrips = new HashSet<MSTTravelTrip>();
            this.TravelTrips = new HashSet<TravelTrip>();
            this.TravelTripTaskElementCustomFieldValueXREFs = new HashSet<TravelTripTaskElementCustomFieldValueXREF>();
        }
    
        public int TravelTripTaskElementID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public string TravelTaskID { get; set; }
        public string TravelTaskTitle { get; set; }
        public string TravelTaskDescription { get; set; }
        public int BOEID { get; set; }
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        public Nullable<System.DateTime> TaskEndDate { get; set; }
        public int SortOrderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTTravelTrip> MSTTravelTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelTrip> TravelTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelTripTaskElementCustomFieldValueXREF> TravelTripTaskElementCustomFieldValueXREFs { get; set; }
        public virtual BOE BOE { get; set; }
    }
}
