//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.TravelTrips = new HashSet<TravelTrip>();
        }
    
        public int TripID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int TravelMiscRateID { get; set; }
        public int DepartureLocationID { get; set; }
        public int DestinationLocationID { get; set; }
        public int PerDiemID { get; set; }
        public decimal TransportationFare { get; set; }
        public int RoundTripMiles { get; set; }
        public int FareLastUpdateETIUserID { get; set; }
        public System.DateTime FareLastUpdateDT { get; set; }
        public bool TripInUse { get; set; }
        public Nullable<System.DateTime> LastUsedDT { get; set; }
        public decimal RentalCarRate { get; set; }
        public string DepartureLocationCode { get; set; }
        public string DestinationLocationCode { get; set; }
    
        public virtual ETIuser ETIuser { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual PerDiem PerDiem { get; set; }
        public virtual TravelMiscRate TravelMiscRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelTrip> TravelTrips { get; set; }
    }
}
