//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBS_CLIN_BOE_XREF1
    {
        public int WCBID { get; set; }
        public Nullable<int> WBSID { get; set; }
        public Nullable<int> CLINID { get; set; }
        public Nullable<int> BOEID { get; set; }
        public int VersionID { get; set; }
    }
}
