//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkspaceLockedPerDiem
    {
        public int WorkspaceLockedPerDiemID { get; set; }
        public int PerDiemID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public string PerDiemDestination { get; set; }
        public string Qualification { get; set; }
        public decimal HotelRate { get; set; }
        public decimal MIERate { get; set; }
        public string PerDiemNotes { get; set; }
        public Nullable<int> PerDiemLastUpdateETIUserID { get; set; }
        public System.DateTime PerDiemLastUpdateDT { get; set; }
        public int WorkspaceID { get; set; }
    
        public virtual Workspace Workspace { get; set; }
    }
}
