//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkspaceEmailXREF
    {
        public int WorkspaceEmailID { get; set; }
        public int EmailID { get; set; }
        public int WorkspaceID { get; set; }
        public bool TurnOn { get; set; }
        public System.DateTime UpdateDT { get; set; }
    
        public virtual EmailLU EmailLU { get; set; }
        public virtual Workspace Workspace { get; set; }
    }
}
