//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkspaceStateHistory
    {
        public int WorkspaceStateHistoryID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public int WorkspaceID { get; set; }
        public int CurrentWorkspaceStateID { get; set; }
        public int UpdatedWorkspaceStateID { get; set; }
        public int ChangedByETIUserID { get; set; }
    
        public virtual ETIuser ETIuser { get; set; }
        public virtual WorkspaceStateLU WorkspaceStateLU { get; set; }
        public virtual WorkspaceStateLU WorkspaceStateLU1 { get; set; }
        public virtual Workspace Workspace { get; set; }
    }
}
