//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkspaceLockedTravelMiscRate
    {
        public int WorkspaceLockedTravelMiscRateID { get; set; }
        public int TravelMiscRateID { get; set; }
        public System.DateTime UpdateDT { get; set; }
        public string TransportationMode { get; set; }
        public decimal MiscellaneousRate { get; set; }
        public byte SortCode { get; set; }
        public bool MiscRateInUse { get; set; }
        public int WorkspaceID { get; set; }
    
        public virtual Workspace Workspace { get; set; }
    }
}
