//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenBOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkspaceVersion
    {
        public int VersionID { get; set; }
        public string VersionName { get; set; }
        public System.DateTime VersionCreated { get; set; }
        public int CreatedByETIUserID { get; set; }
        public int WorkspaceStateID { get; set; }
        public int WorkspaceID { get; set; }
    
        public virtual ETIuser ETIuser { get; set; }
        public virtual WorkspaceStateLU WorkspaceStateLU { get; set; }
        public virtual Workspace Workspace { get; set; }
    }
}
