//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IESEntities : DbContext
    {
        public IESEntities()
            : base("name=IESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BurdenPoolLU> BurdenPoolLUs { get; set; }
        public virtual DbSet<BurdenElementLU> BurdenElementLUs { get; set; }
        public virtual DbSet<CategoryLU> CategoryLUs { get; set; }
        public virtual DbSet<CobraCode1LU> CobraCode1LU { get; set; }
        public virtual DbSet<ProPricerBurdenRateMap> ProPricerBurdenRateMaps { get; set; }
        public virtual DbSet<ProPricerRateCodeXref> ProPricerRateCodeXrefs { get; set; }
        public virtual DbSet<RateCode> RateCodes { get; set; }
        public virtual DbSet<RateCodeExtensionLU> RateCodeExtensionLUs { get; set; }
        public virtual DbSet<RateCodeYear> RateCodeYears { get; set; }
        public virtual DbSet<RateTypeLU> RateTypeLUs { get; set; }
        public virtual DbSet<ResourceTypeLU> ResourceTypeLUs { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SectionContentTypeLU> SectionContentTypeLUs { get; set; }
        public virtual DbSet<CobraFiscalYearLU> CobraFiscalYearLUs { get; set; }
        public virtual DbSet<Revision> Revisions { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<ResourceClassLU> ResourceClassLUs { get; set; }
        public virtual DbSet<FileAttachment> FileAttachments { get; set; }
        public virtual DbSet<RDSBRateCodeXref> RDSBRateCodeXrefs { get; set; }
        public virtual DbSet<RDSBSectionXref> RDSBSectionXrefs { get; set; }
        public virtual DbSet<RDSBDocumentInformation> RDSBDocumentInformations { get; set; }
        public virtual DbSet<RateConfig> RateConfigs { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<RateCodeReplication> RateCodeReplications { get; set; }
        public virtual DbSet<OfflineApplication> OfflineApplications { get; set; }
        public virtual DbSet<BoeDatabaseVersion> BoeDatabaseVersions { get; set; }
        public virtual DbSet<DisclosureTypeLU> DisclosureTypeLUs { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
    
        public virtual int deleteCobraFiscalYear(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteCobraFiscalYear", idParameter, updateDateParameter);
        }
    
        public virtual int deleteProPricerBurdenRateMap(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteProPricerBurdenRateMap", idParameter, updateDateParameter);
        }
    
        public virtual int deleteProPricerRateCodeXref(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteProPricerRateCodeXref", idParameter, updateDateParameter);
        }
    
        public virtual int deleteRateCode(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteRateCode", idParameter, updateDateParameter);
        }
    
        public virtual int deleteRateCodeYear(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteRateCodeYear", idParameter, updateDateParameter);
        }
    
        public virtual int deleteRevision(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteRevision", idParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<ExportCobraRates_Result> ExportCobraRates(Nullable<int> revisionID)
        {
            var revisionIDParameter = revisionID.HasValue ?
                new ObjectParameter("RevisionID", revisionID) :
                new ObjectParameter("RevisionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExportCobraRates_Result>("ExportCobraRates", revisionIDParameter);
        }
    
        public virtual ObjectResult<ExportProPricerBurdenRates_Result> ExportProPricerBurdenRates(Nullable<int> revisionID)
        {
            var revisionIDParameter = revisionID.HasValue ?
                new ObjectParameter("RevisionID", revisionID) :
                new ObjectParameter("RevisionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExportProPricerBurdenRates_Result>("ExportProPricerBurdenRates", revisionIDParameter);
        }
    
        public virtual ObjectResult<ExportProPricerDirectRates_Result> ExportProPricerDirectRates(Nullable<int> revisionID)
        {
            var revisionIDParameter = revisionID.HasValue ?
                new ObjectParameter("RevisionID", revisionID) :
                new ObjectParameter("RevisionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExportProPricerDirectRates_Result>("ExportProPricerDirectRates", revisionIDParameter);
        }
    
        public virtual ObjectResult<GetProPricerBurdenRateCodes_Result> GetProPricerBurdenRateCodes(Nullable<int> revisionID)
        {
            var revisionIDParameter = revisionID.HasValue ?
                new ObjectParameter("RevisionID", revisionID) :
                new ObjectParameter("RevisionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProPricerBurdenRateCodes_Result>("GetProPricerBurdenRateCodes", revisionIDParameter);
        }
    
        public virtual int GetRateCodeList(Nullable<int> revisionID, string startYear, string endYear)
        {
            var revisionIDParameter = revisionID.HasValue ?
                new ObjectParameter("RevisionID", revisionID) :
                new ObjectParameter("RevisionID", typeof(int));
    
            var startYearParameter = startYear != null ?
                new ObjectParameter("StartYear", startYear) :
                new ObjectParameter("StartYear", typeof(string));
    
            var endYearParameter = endYear != null ?
                new ObjectParameter("EndYear", endYear) :
                new ObjectParameter("EndYear", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetRateCodeList", revisionIDParameter, startYearParameter, endYearParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertCobraFiscalYear(Nullable<int> id, Nullable<System.DateTime> updateDate, Nullable<int> year, Nullable<System.DateTime> fiscalYearStartDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var fiscalYearStartDateParameter = fiscalYearStartDate.HasValue ?
                new ObjectParameter("FiscalYearStartDate", fiscalYearStartDate) :
                new ObjectParameter("FiscalYearStartDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertCobraFiscalYear", idParameter, updateDateParameter, yearParameter, fiscalYearStartDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertProPricerRateCodeXref(Nullable<int> id, Nullable<System.DateTime> updateDate, Nullable<int> rateCodeID, string description, Nullable<int> rateCodeExtensionID, Nullable<int> resourceClassID)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var rateCodeIDParameter = rateCodeID.HasValue ?
                new ObjectParameter("RateCodeID", rateCodeID) :
                new ObjectParameter("RateCodeID", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var rateCodeExtensionIDParameter = rateCodeExtensionID.HasValue ?
                new ObjectParameter("RateCodeExtensionID", rateCodeExtensionID) :
                new ObjectParameter("RateCodeExtensionID", typeof(int));
    
            var resourceClassIDParameter = resourceClassID.HasValue ?
                new ObjectParameter("ResourceClassID", resourceClassID) :
                new ObjectParameter("ResourceClassID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertProPricerRateCodeXref", idParameter, updateDateParameter, rateCodeIDParameter, descriptionParameter, rateCodeExtensionIDParameter, resourceClassIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertRevision(Nullable<int> id, Nullable<System.DateTime> updateDate, string revision, string history, string createdBy, Nullable<int> startYear, Nullable<int> endYear, string releaseNotes)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var revisionParameter = revision != null ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(string));
    
            var historyParameter = history != null ?
                new ObjectParameter("History", history) :
                new ObjectParameter("History", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var startYearParameter = startYear.HasValue ?
                new ObjectParameter("StartYear", startYear) :
                new ObjectParameter("StartYear", typeof(int));
    
            var endYearParameter = endYear.HasValue ?
                new ObjectParameter("EndYear", endYear) :
                new ObjectParameter("EndYear", typeof(int));
    
            var releaseNotesParameter = releaseNotes != null ?
                new ObjectParameter("ReleaseNotes", releaseNotes) :
                new ObjectParameter("ReleaseNotes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertRevision", idParameter, updateDateParameter, revisionParameter, historyParameter, createdByParameter, startYearParameter, endYearParameter, releaseNotesParameter);
        }
    
        public virtual int deleteSection(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteSection", idParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertSection(Nullable<int> id, Nullable<System.DateTime> updateDate, Nullable<int> revisionID, Nullable<int> parentID, Nullable<int> displayOrder, string title, string textContent, Nullable<int> sectionContentTypeID, Nullable<bool> isInternalSection, Nullable<bool> displayRateCode, Nullable<int> revisionUniqueSectionId, Nullable<bool> isRdsbRequired, Nullable<bool> sectionContainsCasbDisclosure, Nullable<bool> sectionContainsNonCompliance, string office, string agency, string lMBA, string name, string street, string cityST, string phone, string email, string other, Nullable<bool> includeInCoversheet)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var revisionIDParameter = revisionID.HasValue ?
                new ObjectParameter("RevisionID", revisionID) :
                new ObjectParameter("RevisionID", typeof(int));
    
            var parentIDParameter = parentID.HasValue ?
                new ObjectParameter("ParentID", parentID) :
                new ObjectParameter("ParentID", typeof(int));
    
            var displayOrderParameter = displayOrder.HasValue ?
                new ObjectParameter("DisplayOrder", displayOrder) :
                new ObjectParameter("DisplayOrder", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var textContentParameter = textContent != null ?
                new ObjectParameter("TextContent", textContent) :
                new ObjectParameter("TextContent", typeof(string));
    
            var sectionContentTypeIDParameter = sectionContentTypeID.HasValue ?
                new ObjectParameter("SectionContentTypeID", sectionContentTypeID) :
                new ObjectParameter("SectionContentTypeID", typeof(int));
    
            var isInternalSectionParameter = isInternalSection.HasValue ?
                new ObjectParameter("IsInternalSection", isInternalSection) :
                new ObjectParameter("IsInternalSection", typeof(bool));
    
            var displayRateCodeParameter = displayRateCode.HasValue ?
                new ObjectParameter("DisplayRateCode", displayRateCode) :
                new ObjectParameter("DisplayRateCode", typeof(bool));
    
            var revisionUniqueSectionIdParameter = revisionUniqueSectionId.HasValue ?
                new ObjectParameter("RevisionUniqueSectionId", revisionUniqueSectionId) :
                new ObjectParameter("RevisionUniqueSectionId", typeof(int));
    
            var isRdsbRequiredParameter = isRdsbRequired.HasValue ?
                new ObjectParameter("IsRdsbRequired", isRdsbRequired) :
                new ObjectParameter("IsRdsbRequired", typeof(bool));
    
            var sectionContainsCasbDisclosureParameter = sectionContainsCasbDisclosure.HasValue ?
                new ObjectParameter("SectionContainsCasbDisclosure", sectionContainsCasbDisclosure) :
                new ObjectParameter("SectionContainsCasbDisclosure", typeof(bool));
    
            var sectionContainsNonComplianceParameter = sectionContainsNonCompliance.HasValue ?
                new ObjectParameter("SectionContainsNonCompliance", sectionContainsNonCompliance) :
                new ObjectParameter("SectionContainsNonCompliance", typeof(bool));
    
            var officeParameter = office != null ?
                new ObjectParameter("Office", office) :
                new ObjectParameter("Office", typeof(string));
    
            var agencyParameter = agency != null ?
                new ObjectParameter("Agency", agency) :
                new ObjectParameter("Agency", typeof(string));
    
            var lMBAParameter = lMBA != null ?
                new ObjectParameter("LMBA", lMBA) :
                new ObjectParameter("LMBA", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var streetParameter = street != null ?
                new ObjectParameter("Street", street) :
                new ObjectParameter("Street", typeof(string));
    
            var citySTParameter = cityST != null ?
                new ObjectParameter("CityST", cityST) :
                new ObjectParameter("CityST", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var otherParameter = other != null ?
                new ObjectParameter("Other", other) :
                new ObjectParameter("Other", typeof(string));
    
            var includeInCoversheetParameter = includeInCoversheet.HasValue ?
                new ObjectParameter("IncludeInCoversheet", includeInCoversheet) :
                new ObjectParameter("IncludeInCoversheet", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertSection", idParameter, updateDateParameter, revisionIDParameter, parentIDParameter, displayOrderParameter, titleParameter, textContentParameter, sectionContentTypeIDParameter, isInternalSectionParameter, displayRateCodeParameter, revisionUniqueSectionIdParameter, isRdsbRequiredParameter, sectionContainsCasbDisclosureParameter, sectionContainsNonComplianceParameter, officeParameter, agencyParameter, lMBAParameter, nameParameter, streetParameter, citySTParameter, phoneParameter, emailParameter, otherParameter, includeInCoversheetParameter);
        }
    
        public virtual ObjectResult<copyRevision_Result> copyRevision(Nullable<int> id, string newRevision, string newHistory, string newCreatedBy, string newReleaseNotes)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var newRevisionParameter = newRevision != null ?
                new ObjectParameter("NewRevision", newRevision) :
                new ObjectParameter("NewRevision", typeof(string));
    
            var newHistoryParameter = newHistory != null ?
                new ObjectParameter("NewHistory", newHistory) :
                new ObjectParameter("NewHistory", typeof(string));
    
            var newCreatedByParameter = newCreatedBy != null ?
                new ObjectParameter("NewCreatedBy", newCreatedBy) :
                new ObjectParameter("NewCreatedBy", typeof(string));
    
            var newReleaseNotesParameter = newReleaseNotes != null ?
                new ObjectParameter("NewReleaseNotes", newReleaseNotes) :
                new ObjectParameter("NewReleaseNotes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<copyRevision_Result>("copyRevision", idParameter, newRevisionParameter, newHistoryParameter, newCreatedByParameter, newReleaseNotesParameter);
        }
    
        public virtual int deleteBurdenPoolLU(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteBurdenPoolLU", idParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertBurdenPoolLU(Nullable<int> id, Nullable<System.DateTime> updateDate, Nullable<int> revisionID, string burdenPool, string description, Nullable<bool> isGaT2ApplicableForMissionSolutions, Nullable<bool> includeGaT2InBurdAndCommBurdTables, Nullable<bool> isCommercial, Nullable<bool> excludeFCCOM)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var revisionIDParameter = revisionID.HasValue ?
                new ObjectParameter("RevisionID", revisionID) :
                new ObjectParameter("RevisionID", typeof(int));
    
            var burdenPoolParameter = burdenPool != null ?
                new ObjectParameter("BurdenPool", burdenPool) :
                new ObjectParameter("BurdenPool", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var isGaT2ApplicableForMissionSolutionsParameter = isGaT2ApplicableForMissionSolutions.HasValue ?
                new ObjectParameter("IsGaT2ApplicableForMissionSolutions", isGaT2ApplicableForMissionSolutions) :
                new ObjectParameter("IsGaT2ApplicableForMissionSolutions", typeof(bool));
    
            var includeGaT2InBurdAndCommBurdTablesParameter = includeGaT2InBurdAndCommBurdTables.HasValue ?
                new ObjectParameter("IncludeGaT2InBurdAndCommBurdTables", includeGaT2InBurdAndCommBurdTables) :
                new ObjectParameter("IncludeGaT2InBurdAndCommBurdTables", typeof(bool));
    
            var isCommercialParameter = isCommercial.HasValue ?
                new ObjectParameter("IsCommercial", isCommercial) :
                new ObjectParameter("IsCommercial", typeof(bool));
    
            var excludeFCCOMParameter = excludeFCCOM.HasValue ?
                new ObjectParameter("ExcludeFCCOM", excludeFCCOM) :
                new ObjectParameter("ExcludeFCCOM", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertBurdenPoolLU", idParameter, updateDateParameter, revisionIDParameter, burdenPoolParameter, descriptionParameter, isGaT2ApplicableForMissionSolutionsParameter, includeGaT2InBurdAndCommBurdTablesParameter, isCommercialParameter, excludeFCCOMParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertRateCode(Nullable<int> id, Nullable<System.DateTime> updateDate, Nullable<int> revisionID, Nullable<int> categoryID, string description, Nullable<int> sectionID, string rateCode, Nullable<int> resourceTypeID, Nullable<int> governmentBurdenPoolID, Nullable<int> commercialBurdenPoolID, Nullable<int> rateTypeID, string cobraRateSet, Nullable<int> cobraCode1ID)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var revisionIDParameter = revisionID.HasValue ?
                new ObjectParameter("RevisionID", revisionID) :
                new ObjectParameter("RevisionID", typeof(int));
    
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var sectionIDParameter = sectionID.HasValue ?
                new ObjectParameter("SectionID", sectionID) :
                new ObjectParameter("SectionID", typeof(int));
    
            var rateCodeParameter = rateCode != null ?
                new ObjectParameter("RateCode", rateCode) :
                new ObjectParameter("RateCode", typeof(string));
    
            var resourceTypeIDParameter = resourceTypeID.HasValue ?
                new ObjectParameter("ResourceTypeID", resourceTypeID) :
                new ObjectParameter("ResourceTypeID", typeof(int));
    
            var governmentBurdenPoolIDParameter = governmentBurdenPoolID.HasValue ?
                new ObjectParameter("GovernmentBurdenPoolID", governmentBurdenPoolID) :
                new ObjectParameter("GovernmentBurdenPoolID", typeof(int));
    
            var commercialBurdenPoolIDParameter = commercialBurdenPoolID.HasValue ?
                new ObjectParameter("CommercialBurdenPoolID", commercialBurdenPoolID) :
                new ObjectParameter("CommercialBurdenPoolID", typeof(int));
    
            var rateTypeIDParameter = rateTypeID.HasValue ?
                new ObjectParameter("RateTypeID", rateTypeID) :
                new ObjectParameter("RateTypeID", typeof(int));
    
            var cobraRateSetParameter = cobraRateSet != null ?
                new ObjectParameter("CobraRateSet", cobraRateSet) :
                new ObjectParameter("CobraRateSet", typeof(string));
    
            var cobraCode1IDParameter = cobraCode1ID.HasValue ?
                new ObjectParameter("CobraCode1ID", cobraCode1ID) :
                new ObjectParameter("CobraCode1ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertRateCode", idParameter, updateDateParameter, revisionIDParameter, categoryIDParameter, descriptionParameter, sectionIDParameter, rateCodeParameter, resourceTypeIDParameter, governmentBurdenPoolIDParameter, commercialBurdenPoolIDParameter, rateTypeIDParameter, cobraRateSetParameter, cobraCode1IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertRateCodeYear(Nullable<int> id, Nullable<System.DateTime> updateDate, Nullable<int> rateCodeID, Nullable<int> year, Nullable<decimal> rate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var rateCodeIDParameter = rateCodeID.HasValue ?
                new ObjectParameter("RateCodeID", rateCodeID) :
                new ObjectParameter("RateCodeID", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var rateParameter = rate.HasValue ?
                new ObjectParameter("Rate", rate) :
                new ObjectParameter("Rate", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertRateCodeYear", idParameter, updateDateParameter, rateCodeIDParameter, yearParameter, rateParameter);
        }
    
        public virtual ObjectResult<publishRevision_Result> publishRevision(Nullable<int> id, Nullable<System.DateTime> updateDate, string publishedBy, string history, string releaseNotes, Nullable<System.DateTime> datePublished)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var publishedByParameter = publishedBy != null ?
                new ObjectParameter("PublishedBy", publishedBy) :
                new ObjectParameter("PublishedBy", typeof(string));
    
            var historyParameter = history != null ?
                new ObjectParameter("History", history) :
                new ObjectParameter("History", typeof(string));
    
            var releaseNotesParameter = releaseNotes != null ?
                new ObjectParameter("ReleaseNotes", releaseNotes) :
                new ObjectParameter("ReleaseNotes", typeof(string));
    
            var datePublishedParameter = datePublished.HasValue ?
                new ObjectParameter("DatePublished", datePublished) :
                new ObjectParameter("DatePublished", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<publishRevision_Result>("publishRevision", idParameter, updateDateParameter, publishedByParameter, historyParameter, releaseNotesParameter, datePublishedParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertProPricerBurdenRateMap(Nullable<int> id, Nullable<System.DateTime> updateDate, Nullable<int> burdenPoolID, Nullable<int> burdenElementID, Nullable<int> rateCodeID)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var burdenPoolIDParameter = burdenPoolID.HasValue ?
                new ObjectParameter("BurdenPoolID", burdenPoolID) :
                new ObjectParameter("BurdenPoolID", typeof(int));
    
            var burdenElementIDParameter = burdenElementID.HasValue ?
                new ObjectParameter("BurdenElementID", burdenElementID) :
                new ObjectParameter("BurdenElementID", typeof(int));
    
            var rateCodeIDParameter = rateCodeID.HasValue ?
                new ObjectParameter("RateCodeID", rateCodeID) :
                new ObjectParameter("RateCodeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertProPricerBurdenRateMap", idParameter, updateDateParameter, burdenPoolIDParameter, burdenElementIDParameter, rateCodeIDParameter);
        }
    
        public virtual int upsertUserLog(string nTID, string displayName, string application)
        {
            var nTIDParameter = nTID != null ?
                new ObjectParameter("NTID", nTID) :
                new ObjectParameter("NTID", typeof(string));
    
            var displayNameParameter = displayName != null ?
                new ObjectParameter("DisplayName", displayName) :
                new ObjectParameter("DisplayName", typeof(string));
    
            var applicationParameter = application != null ?
                new ObjectParameter("Application", application) :
                new ObjectParameter("Application", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upsertUserLog", nTIDParameter, displayNameParameter, applicationParameter);
        }
    
        public virtual int deleteFileAttachment(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteFileAttachment", idParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertFileAttachment(Nullable<int> id, Nullable<System.DateTime> updateDate, string name, string link, Nullable<int> sectionId, Nullable<int> revisionId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var linkParameter = link != null ?
                new ObjectParameter("Link", link) :
                new ObjectParameter("Link", typeof(string));
    
            var sectionIdParameter = sectionId.HasValue ?
                new ObjectParameter("SectionId", sectionId) :
                new ObjectParameter("SectionId", typeof(int));
    
            var revisionIdParameter = revisionId.HasValue ?
                new ObjectParameter("RevisionId", revisionId) :
                new ObjectParameter("RevisionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertFileAttachment", idParameter, updateDateParameter, nameParameter, linkParameter, sectionIdParameter, revisionIdParameter);
        }
    
        public virtual int remapSectionReferences(Nullable<int> id, Nullable<System.DateTime> updateDate, Nullable<int> newId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var newIdParameter = newId.HasValue ?
                new ObjectParameter("NewId", newId) :
                new ObjectParameter("NewId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("remapSectionReferences", idParameter, updateDateParameter, newIdParameter);
        }
    
        public virtual int deleteRDSBDocumentInformation(Nullable<int> id, Nullable<System.DateTime> lastUpdateDT)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var lastUpdateDTParameter = lastUpdateDT.HasValue ?
                new ObjectParameter("LastUpdateDT", lastUpdateDT) :
                new ObjectParameter("LastUpdateDT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteRDSBDocumentInformation", idParameter, lastUpdateDTParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertRDSBDocumentInformation(Nullable<int> id, Nullable<System.DateTime> lastUpdateDT, Nullable<int> pTMProposalID, string createdBy, Nullable<int> rDMRevisionID, Nullable<int> startYear, Nullable<int> endYear, string parentSection)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var lastUpdateDTParameter = lastUpdateDT.HasValue ?
                new ObjectParameter("LastUpdateDT", lastUpdateDT) :
                new ObjectParameter("LastUpdateDT", typeof(System.DateTime));
    
            var pTMProposalIDParameter = pTMProposalID.HasValue ?
                new ObjectParameter("PTMProposalID", pTMProposalID) :
                new ObjectParameter("PTMProposalID", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var rDMRevisionIDParameter = rDMRevisionID.HasValue ?
                new ObjectParameter("RDMRevisionID", rDMRevisionID) :
                new ObjectParameter("RDMRevisionID", typeof(int));
    
            var startYearParameter = startYear.HasValue ?
                new ObjectParameter("StartYear", startYear) :
                new ObjectParameter("StartYear", typeof(int));
    
            var endYearParameter = endYear.HasValue ?
                new ObjectParameter("EndYear", endYear) :
                new ObjectParameter("EndYear", typeof(int));
    
            var parentSectionParameter = parentSection != null ?
                new ObjectParameter("ParentSection", parentSection) :
                new ObjectParameter("ParentSection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertRDSBDocumentInformation", idParameter, lastUpdateDTParameter, pTMProposalIDParameter, createdByParameter, rDMRevisionIDParameter, startYearParameter, endYearParameter, parentSectionParameter);
        }
    
        public virtual int deleteBanner(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteBanner", idParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertBanner(Nullable<int> id, Nullable<System.DateTime> updateDate, string selectedApps, Nullable<System.DateTime> startDate, Nullable<int> hoursToShow, string bannerText, Nullable<bool> turnOffTicker)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var selectedAppsParameter = selectedApps != null ?
                new ObjectParameter("SelectedApps", selectedApps) :
                new ObjectParameter("SelectedApps", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var hoursToShowParameter = hoursToShow.HasValue ?
                new ObjectParameter("HoursToShow", hoursToShow) :
                new ObjectParameter("HoursToShow", typeof(int));
    
            var bannerTextParameter = bannerText != null ?
                new ObjectParameter("BannerText", bannerText) :
                new ObjectParameter("BannerText", typeof(string));
    
            var turnOffTickerParameter = turnOffTicker.HasValue ?
                new ObjectParameter("TurnOffTicker", turnOffTicker) :
                new ObjectParameter("TurnOffTicker", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertBanner", idParameter, updateDateParameter, selectedAppsParameter, startDateParameter, hoursToShowParameter, bannerTextParameter, turnOffTickerParameter);
        }
    
        public virtual int deleteReplication(Nullable<int> id, Nullable<System.DateTime> updateDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteReplication", idParameter, updateDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> upsertReplication(Nullable<int> id, Nullable<System.DateTime> updateDate, string from, string to)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            var fromParameter = from != null ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("upsertReplication", idParameter, updateDateParameter, fromParameter, toParameter);
        }
    
        public virtual ObjectResult<verifyRateCodeReplication_Result> verifyRateCodeReplication(Nullable<int> revisionId)
        {
            var revisionIdParameter = revisionId.HasValue ?
                new ObjectParameter("RevisionId", revisionId) :
                new ObjectParameter("RevisionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verifyRateCodeReplication_Result>("verifyRateCodeReplication", revisionIdParameter);
        }
    
        public virtual int updateOfflineApplication(string applicationName, Nullable<bool> isOffline, Nullable<System.DateTime> updateDate)
        {
            var applicationNameParameter = applicationName != null ?
                new ObjectParameter("ApplicationName", applicationName) :
                new ObjectParameter("ApplicationName", typeof(string));
    
            var isOfflineParameter = isOffline.HasValue ?
                new ObjectParameter("IsOffline", isOffline) :
                new ObjectParameter("IsOffline", typeof(bool));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateOfflineApplication", applicationNameParameter, isOfflineParameter, updateDateParameter);
        }
    
        public virtual int deleteProPricerRateCodeXrefviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteProPricerRateCodeXrefviaTableParameter");
        }
    
        public virtual int deleteRateCodeviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteRateCodeviaTableParameter");
        }
    
        public virtual ObjectResult<string> ELMAH_GetErrorsXml(string application, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter totalCount)
        {
            var applicationParameter = application != null ?
                new ObjectParameter("Application", application) :
                new ObjectParameter("Application", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ELMAH_GetErrorsXml", applicationParameter, pageIndexParameter, pageSizeParameter, totalCount);
        }
    
        public virtual ObjectResult<string> ELMAH_GetErrorXml(string application, Nullable<System.Guid> errorId)
        {
            var applicationParameter = application != null ?
                new ObjectParameter("Application", application) :
                new ObjectParameter("Application", typeof(string));
    
            var errorIdParameter = errorId.HasValue ?
                new ObjectParameter("ErrorId", errorId) :
                new ObjectParameter("ErrorId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ELMAH_GetErrorXml", applicationParameter, errorIdParameter);
        }
    
        public virtual int ELMAH_LogError(Nullable<System.Guid> errorId, string application, string host, string type, string source, string message, string user, string allXml, Nullable<int> statusCode, Nullable<System.DateTime> timeUtc)
        {
            var errorIdParameter = errorId.HasValue ?
                new ObjectParameter("ErrorId", errorId) :
                new ObjectParameter("ErrorId", typeof(System.Guid));
    
            var applicationParameter = application != null ?
                new ObjectParameter("Application", application) :
                new ObjectParameter("Application", typeof(string));
    
            var hostParameter = host != null ?
                new ObjectParameter("Host", host) :
                new ObjectParameter("Host", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var allXmlParameter = allXml != null ?
                new ObjectParameter("AllXml", allXml) :
                new ObjectParameter("AllXml", typeof(string));
    
            var statusCodeParameter = statusCode.HasValue ?
                new ObjectParameter("StatusCode", statusCode) :
                new ObjectParameter("StatusCode", typeof(int));
    
            var timeUtcParameter = timeUtc.HasValue ?
                new ObjectParameter("TimeUtc", timeUtc) :
                new ObjectParameter("TimeUtc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELMAH_LogError", errorIdParameter, applicationParameter, hostParameter, typeParameter, sourceParameter, messageParameter, userParameter, allXmlParameter, statusCodeParameter, timeUtcParameter);
        }
    
        public virtual int insertProPricerRateCodeXrefviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertProPricerRateCodeXrefviaTableParameter");
        }
    
        public virtual int insertRateCodeviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertRateCodeviaTableParameter");
        }
    
        public virtual int insertRateCodeYearviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertRateCodeYearviaTableParameter");
        }
    
        public virtual int insertRDSBRateCodeXrefviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertRDSBRateCodeXrefviaTableParameter");
        }
    
        public virtual int insertRDSBSectionXrefviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertRDSBSectionXrefviaTableParameter");
        }
    
        public virtual int updateCobraDetailviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateCobraDetailviaTableParameter");
        }
    
        public virtual int UpdateDbVersion(string dbVersion, string appVersion)
        {
            var dbVersionParameter = dbVersion != null ?
                new ObjectParameter("DbVersion", dbVersion) :
                new ObjectParameter("DbVersion", typeof(string));
    
            var appVersionParameter = appVersion != null ?
                new ObjectParameter("AppVersion", appVersion) :
                new ObjectParameter("AppVersion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDbVersion", dbVersionParameter, appVersionParameter);
        }
    
        public virtual int updateProPricerRateCodeXrefviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateProPricerRateCodeXrefviaTableParameter");
        }
    
        public virtual int updateRateCodeviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateRateCodeviaTableParameter");
        }
    
        public virtual int updateRateCodeYearviaTableParameter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateRateCodeYearviaTableParameter");
        }
    }
}
