# Exclude files and directories ending with "Test", "Tests", "test", or "tests"
# Exclude files ending with "Test.cs", "Tests.cs", and files or folders containing "test" in their name
com.fortify.sca.exclude=*/Connected Services/*:**/*Test.cs:/**/*Tests.cs:tests/**:**/*test*/**:**/*tests*/**:**/*test*.*:/**/*Test*.*:/**/*Tests*.*:/**/*test*/:**/*Test*/:**/*Tests*/:**/*Tests/*
