# sonar always just looks for this file
# https,//docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner
# find your coverage schema here, i.e. javascript is sonar.javascript.lcov.reportPaths
# https,//docs.sonarqube.org/latest/analysis/coverage/

# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Exclude all classes in the "tst" directory and file named index.html in src directory
# Separate the file list with commas
sonar.exclusions=**/*Test.cs,/**/*Tests.cs,tests/**,**/*test*/**,**/*tests*/**,**/*test*.*,/**/*Test*.*,/**/*Tests*.*,/**/*test*/,**/*Test*/,**/*Tests*/,**/*Tests/*
