<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="IESEntityModel.Context.tt" />
    <None Remove="IESEntityModel.tt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="IESEntityModel.Context.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <DependentUpon>IESEntityModel.edmx</DependentUpon>
      <LastGenOutput>IESEntityModel.Context.cs</LastGenOutput>
    </Content>
    <Content Include="IESEntityModel.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <DependentUpon>IESEntityModel.edmx</DependentUpon>
      <LastGenOutput>IESEntityModel.cs</LastGenOutput>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

	<ItemGroup>
		<Compile Include="Banner.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="BoeDatabaseVersion.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="BurdenElementLU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="BurdenPoolLU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="CategoryLU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="CobraCode1LU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="CobraFiscalYearLU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="copyRevision_Result.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="DisclosureTypeLU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="ELMAH_Error.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="ExportCobraRates_Result.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="ExportProPricerBurdenRates_Result.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="ExportProPricerDirectRates_Result.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="FileAttachment.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="GetPricingCodeMappings_Result.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="GetProPricerBurdenRateCodes_Result.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="IESEntityModel.Context.cs">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>IESEntityModel.Context.tt</DependentUpon>
		</Compile>
		<Compile Include="IESEntityModel.cs">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="OfflineApplication.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="RateCodeReplication.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="RateConfig.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="RDSBDocumentInformation.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="RDSBRateCodeXref.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="RDSBSectionXref.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="ResourceClassLU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="UserLog.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="verifyRateCodeReplication_Result.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Content Include="IESEntityModel.Designer.cs">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>IESEntityModel.edmx</DependentUpon>
		</Content>
		<Compile Include="Properties\AssemblyInfo.cs" />
		<Compile Include="ProPricerBurdenRateMap.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="ProPricerRateCodeXref.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="publishRevision_Result.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="RateCode.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="RateCodeExtensionLU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="RateCodeYear.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="RateTypeLU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="ResourceTypeLU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="Revision.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="Section.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
		<Compile Include="SectionContentTypeLU.cs">
			<DependentUpon>IESEntityModel.tt</DependentUpon>
		</Compile>
	</ItemGroup>

  <ItemGroup>
	<EntityDeploy Include="IESEntityModel.edmx">
		<Generator>EntityModelCodeGenerator</Generator>
		<LastGenOutput>IESEntityModel.Designer.cs</LastGenOutput>
	</EntityDeploy>
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>

</Project>
