//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES.Models.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateConfig
    {
        public int ID { get; set; }
        public string RateTarget { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public int Precision { get; set; }
        public Nullable<int> Multiplier { get; set; }
    
        public virtual CategoryLU CategoryLU { get; set; }
    }
}
